// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: ai/podoai_ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Images        []*ImageInput          `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	Videos        []*VideoInput          `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeScanRequest) Reset() {
	*x = AnalyzeScanRequest{}
	mi := &file_ai_podoai_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeScanRequest) ProtoMessage() {}

func (x *AnalyzeScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_podoai_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeScanRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeScanRequest) Descriptor() ([]byte, []int) {
	return file_ai_podoai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeScanRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *AnalyzeScanRequest) GetImages() []*ImageInput {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *AnalyzeScanRequest) GetVideos() []*VideoInput {
	if x != nil {
		return x.Videos
	}
	return nil
}

type ImageInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInput) Reset() {
	*x = ImageInput{}
	mi := &file_ai_podoai_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInput) ProtoMessage() {}

func (x *ImageInput) ProtoReflect() protoreflect.Message {
	mi := &file_ai_podoai_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInput.ProtoReflect.Descriptor instead.
func (*ImageInput) Descriptor() ([]byte, []int) {
	return file_ai_podoai_ai_proto_rawDescGZIP(), []int{1}
}

func (x *ImageInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ImageInput) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type VideoInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInput) Reset() {
	*x = VideoInput{}
	mi := &file_ai_podoai_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInput) ProtoMessage() {}

func (x *VideoInput) ProtoReflect() protoreflect.Message {
	mi := &file_ai_podoai_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInput.ProtoReflect.Descriptor instead.
func (*VideoInput) Descriptor() ([]byte, []int) {
	return file_ai_podoai_ai_proto_rawDescGZIP(), []int{2}
}

func (x *VideoInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VideoInput) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VideoInput) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type AnalyzeScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Metrics       *BiomechanicalMetrics  `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeScanResponse) Reset() {
	*x = AnalyzeScanResponse{}
	mi := &file_ai_podoai_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeScanResponse) ProtoMessage() {}

func (x *AnalyzeScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_podoai_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeScanResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeScanResponse) Descriptor() ([]byte, []int) {
	return file_ai_podoai_ai_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzeScanResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *AnalyzeScanResponse) GetMetrics() *BiomechanicalMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type BiomechanicalMetrics struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	FootScore              float64                `protobuf:"fixed64,1,opt,name=foot_score,json=footScore,proto3" json:"foot_score,omitempty"`
	GaitScore              float64                `protobuf:"fixed64,2,opt,name=gait_score,json=gaitScore,proto3" json:"gait_score,omitempty"`
	LeftPronationAngle     float64                `protobuf:"fixed64,3,opt,name=left_pronation_angle,json=leftPronationAngle,proto3" json:"left_pronation_angle,omitempty"`
	RightPronationAngle    float64                `protobuf:"fixed64,4,opt,name=right_pronation_angle,json=rightPronationAngle,proto3" json:"right_pronation_angle,omitempty"`
	LeftArchHeightIndex    float64                `protobuf:"fixed64,5,opt,name=left_arch_height_index,json=leftArchHeightIndex,proto3" json:"left_arch_height_index,omitempty"`
	RightArchHeightIndex   float64                `protobuf:"fixed64,6,opt,name=right_arch_height_index,json=rightArchHeightIndex,proto3" json:"right_arch_height_index,omitempty"`
	LeftHalluxValgusAngle  float64                `protobuf:"fixed64,7,opt,name=left_hallux_valgus_angle,json=leftHalluxValgusAngle,proto3" json:"left_hallux_valgus_angle,omitempty"`
	RightHalluxValgusAngle float64                `protobuf:"fixed64,8,opt,name=right_hallux_valgus_angle,json=rightHalluxValgusAngle,proto3" json:"right_hallux_valgus_angle,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BiomechanicalMetrics) Reset() {
	*x = BiomechanicalMetrics{}
	mi := &file_ai_podoai_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BiomechanicalMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiomechanicalMetrics) ProtoMessage() {}

func (x *BiomechanicalMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_ai_podoai_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiomechanicalMetrics.ProtoReflect.Descriptor instead.
func (*BiomechanicalMetrics) Descriptor() ([]byte, []int) {
	return file_ai_podoai_ai_proto_rawDescGZIP(), []int{4}
}

func (x *BiomechanicalMetrics) GetFootScore() float64 {
	if x != nil {
		return x.FootScore
	}
	return 0
}

func (x *BiomechanicalMetrics) GetGaitScore() float64 {
	if x != nil {
		return x.GaitScore
	}
	return 0
}

func (x *BiomechanicalMetrics) GetLeftPronationAngle() float64 {
	if x != nil {
		return x.LeftPronationAngle
	}
	return 0
}

func (x *BiomechanicalMetrics) GetRightPronationAngle() float64 {
	if x != nil {
		return x.RightPronationAngle
	}
	return 0
}

func (x *BiomechanicalMetrics) GetLeftArchHeightIndex() float64 {
	if x != nil {
		return x.LeftArchHeightIndex
	}
	return 0
}

func (x *BiomechanicalMetrics) GetRightArchHeightIndex() float64 {
	if x != nil {
		return x.RightArchHeightIndex
	}
	return 0
}

func (x *BiomechanicalMetrics) GetLeftHalluxValgusAngle() float64 {
	if x != nil {
		return x.LeftHalluxValgusAngle
	}
	return 0
}

func (x *BiomechanicalMetrics) GetRightHalluxValgusAngle() float64 {
	if x != nil {
		return x.RightHalluxValgusAngle
	}
	return 0
}

// Request to generate LLM report
type GenerateLLMReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Metrics       *BiomechanicalMetrics  `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateLLMReportRequest) Reset() {
	*x = GenerateLLMReportRequest{}
	mi := &file_ai_podoai_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateLLMReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateLLMReportRequest) ProtoMessage() {}

func (x *GenerateLLMReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_podoai_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateLLMReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateLLMReportRequest) Descriptor() ([]byte, []int) {
	return file_ai_podoai_ai_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateLLMReportRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *GenerateLLMReportRequest) GetMetrics() *BiomechanicalMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Response containing generated LLM report
type GenerateLLMReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateLLMReportResponse) Reset() {
	*x = GenerateLLMReportResponse{}
	mi := &file_ai_podoai_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateLLMReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateLLMReportResponse) ProtoMessage() {}

func (x *GenerateLLMReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_podoai_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateLLMReportResponse.ProtoReflect.Descriptor instead.
func (*GenerateLLMReportResponse) Descriptor() ([]byte, []int) {
	return file_ai_podoai_ai_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateLLMReportResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *GenerateLLMReportResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_ai_podoai_ai_proto protoreflect.FileDescriptor

const file_ai_podoai_ai_proto_rawDesc = "" +
	"\n" +
	"\x12ai/podoai_ai.proto\x12\tpodoai.ai\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x01\n" +
	"\x12AnalyzeScanRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12-\n" +
	"\x06images\x18\x02 \x03(\v2\x15.podoai.ai.ImageInputR\x06images\x12-\n" +
	"\x06videos\x18\x03 \x03(\v2\x15.podoai.ai.VideoInputR\x06videos\"4\n" +
	"\n" +
	"ImageInput\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"P\n" +
	"\n" +
	"VideoInput\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\"i\n" +
	"\x13AnalyzeScanResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x129\n" +
	"\ametrics\x18\x02 \x01(\v2\x1f.podoai.ai.BiomechanicalMetricsR\ametrics\"\x9a\x03\n" +
	"\x14BiomechanicalMetrics\x12\x1d\n" +
	"\n" +
	"foot_score\x18\x01 \x01(\x01R\tfootScore\x12\x1d\n" +
	"\n" +
	"gait_score\x18\x02 \x01(\x01R\tgaitScore\x120\n" +
	"\x14left_pronation_angle\x18\x03 \x01(\x01R\x12leftPronationAngle\x122\n" +
	"\x15right_pronation_angle\x18\x04 \x01(\x01R\x13rightPronationAngle\x123\n" +
	"\x16left_arch_height_index\x18\x05 \x01(\x01R\x13leftArchHeightIndex\x125\n" +
	"\x17right_arch_height_index\x18\x06 \x01(\x01R\x14rightArchHeightIndex\x127\n" +
	"\x18left_hallux_valgus_angle\x18\a \x01(\x01R\x15leftHalluxValgusAngle\x129\n" +
	"\x19right_hallux_valgus_angle\x18\b \x01(\x01R\x16rightHalluxValgusAngle\"n\n" +
	"\x18GenerateLLMReportRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x129\n" +
	"\ametrics\x18\x02 \x01(\v2\x1f.podoai.ai.BiomechanicalMetricsR\ametrics\"N\n" +
	"\x19GenerateLLMReportResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary2\xc1\x01\n" +
	"\x11AIAnalysisService\x12L\n" +
	"\vAnalyzeScan\x12\x1d.podoai.ai.AnalyzeScanRequest\x1a\x1e.podoai.ai.AnalyzeScanResponse\x12^\n" +
	"\x11GenerateLLMReport\x12#.podoai.ai.GenerateLLMReportRequest\x1a$.podoai.ai.GenerateLLMReportResponseB+Z)github.com/therehabstreet/podoai/proto/aib\x06proto3"

var (
	file_ai_podoai_ai_proto_rawDescOnce sync.Once
	file_ai_podoai_ai_proto_rawDescData []byte
)

func file_ai_podoai_ai_proto_rawDescGZIP() []byte {
	file_ai_podoai_ai_proto_rawDescOnce.Do(func() {
		file_ai_podoai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_podoai_ai_proto_rawDesc), len(file_ai_podoai_ai_proto_rawDesc)))
	})
	return file_ai_podoai_ai_proto_rawDescData
}

var file_ai_podoai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ai_podoai_ai_proto_goTypes = []any{
	(*AnalyzeScanRequest)(nil),        // 0: podoai.ai.AnalyzeScanRequest
	(*ImageInput)(nil),                // 1: podoai.ai.ImageInput
	(*VideoInput)(nil),                // 2: podoai.ai.VideoInput
	(*AnalyzeScanResponse)(nil),       // 3: podoai.ai.AnalyzeScanResponse
	(*BiomechanicalMetrics)(nil),      // 4: podoai.ai.BiomechanicalMetrics
	(*GenerateLLMReportRequest)(nil),  // 5: podoai.ai.GenerateLLMReportRequest
	(*GenerateLLMReportResponse)(nil), // 6: podoai.ai.GenerateLLMReportResponse
}
var file_ai_podoai_ai_proto_depIdxs = []int32{
	1, // 0: podoai.ai.AnalyzeScanRequest.images:type_name -> podoai.ai.ImageInput
	2, // 1: podoai.ai.AnalyzeScanRequest.videos:type_name -> podoai.ai.VideoInput
	4, // 2: podoai.ai.AnalyzeScanResponse.metrics:type_name -> podoai.ai.BiomechanicalMetrics
	4, // 3: podoai.ai.GenerateLLMReportRequest.metrics:type_name -> podoai.ai.BiomechanicalMetrics
	0, // 4: podoai.ai.AIAnalysisService.AnalyzeScan:input_type -> podoai.ai.AnalyzeScanRequest
	5, // 5: podoai.ai.AIAnalysisService.GenerateLLMReport:input_type -> podoai.ai.GenerateLLMReportRequest
	3, // 6: podoai.ai.AIAnalysisService.AnalyzeScan:output_type -> podoai.ai.AnalyzeScanResponse
	6, // 7: podoai.ai.AIAnalysisService.GenerateLLMReport:output_type -> podoai.ai.GenerateLLMReportResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ai_podoai_ai_proto_init() }
func file_ai_podoai_ai_proto_init() {
	if File_ai_podoai_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_podoai_ai_proto_rawDesc), len(file_ai_podoai_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_podoai_ai_proto_goTypes,
		DependencyIndexes: file_ai_podoai_ai_proto_depIdxs,
		MessageInfos:      file_ai_podoai_ai_proto_msgTypes,
	}.Build()
	File_ai_podoai_ai_proto = out.File
	file_ai_podoai_ai_proto_goTypes = nil
	file_ai_podoai_ai_proto_depIdxs = nil
}
