// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: consumer/podoai_consumer.proto

package consumer

import (
	common "github.com/therehabstreet/podoai/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Age           string                 `protobuf:"bytes,5,opt,name=age,proto3" json:"age,omitempty"`
	Gender        common.Gender          `protobuf:"varint,6,opt,name=gender,proto3,enum=podoai.Gender" json:"gender,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_consumer_podoai_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_consumer_podoai_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_consumer_podoai_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *User) GetGender() common.Gender {
	if x != nil {
		return x.Gender
	}
	return common.Gender(0)
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_consumer_podoai_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consumer_podoai_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_consumer_podoai_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_consumer_podoai_consumer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consumer_podoai_consumer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_consumer_podoai_consumer_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_consumer_podoai_consumer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consumer_podoai_consumer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_consumer_podoai_consumer_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_consumer_podoai_consumer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consumer_podoai_consumer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_consumer_podoai_consumer_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_consumer_podoai_consumer_proto protoreflect.FileDescriptor

const file_consumer_podoai_consumer_proto_rawDesc = "" +
	"\n" +
	"\x1econsumer/podoai_consumer.proto\x12\x0fpodoai_consumer\x1a\x13common/podoai.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x05 \x01(\tR\x03age\x12&\n" +
	"\x06gender\x18\x06 \x01(\x0e2\x0e.podoai.GenderR\x06gender\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"<\n" +
	"\x0fGetUserResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.podoai_consumer.UserR\x04user\">\n" +
	"\x11UpdateUserRequest\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.podoai_consumer.UserR\x04user\"?\n" +
	"\x12UpdateUserResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.podoai_consumer.UserR\x04user2\xb6\x01\n" +
	"\x0fConsumerService\x12L\n" +
	"\aGetUser\x12\x1f.podoai_consumer.GetUserRequest\x1a .podoai_consumer.GetUserResponse\x12U\n" +
	"\n" +
	"UpdateUser\x12\".podoai_consumer.UpdateUserRequest\x1a#.podoai_consumer.UpdateUserResponseB1Z/github.com/therehabstreet/podoai/proto/consumerb\x06proto3"

var (
	file_consumer_podoai_consumer_proto_rawDescOnce sync.Once
	file_consumer_podoai_consumer_proto_rawDescData []byte
)

func file_consumer_podoai_consumer_proto_rawDescGZIP() []byte {
	file_consumer_podoai_consumer_proto_rawDescOnce.Do(func() {
		file_consumer_podoai_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consumer_podoai_consumer_proto_rawDesc), len(file_consumer_podoai_consumer_proto_rawDesc)))
	})
	return file_consumer_podoai_consumer_proto_rawDescData
}

var file_consumer_podoai_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_consumer_podoai_consumer_proto_goTypes = []any{
	(*User)(nil),                  // 0: podoai_consumer.User
	(*GetUserRequest)(nil),        // 1: podoai_consumer.GetUserRequest
	(*GetUserResponse)(nil),       // 2: podoai_consumer.GetUserResponse
	(*UpdateUserRequest)(nil),     // 3: podoai_consumer.UpdateUserRequest
	(*UpdateUserResponse)(nil),    // 4: podoai_consumer.UpdateUserResponse
	(common.Gender)(0),            // 5: podoai.Gender
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_consumer_podoai_consumer_proto_depIdxs = []int32{
	5, // 0: podoai_consumer.User.gender:type_name -> podoai.Gender
	6, // 1: podoai_consumer.User.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: podoai_consumer.User.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: podoai_consumer.GetUserResponse.user:type_name -> podoai_consumer.User
	0, // 4: podoai_consumer.UpdateUserRequest.user:type_name -> podoai_consumer.User
	0, // 5: podoai_consumer.UpdateUserResponse.user:type_name -> podoai_consumer.User
	1, // 6: podoai_consumer.ConsumerService.GetUser:input_type -> podoai_consumer.GetUserRequest
	3, // 7: podoai_consumer.ConsumerService.UpdateUser:input_type -> podoai_consumer.UpdateUserRequest
	2, // 8: podoai_consumer.ConsumerService.GetUser:output_type -> podoai_consumer.GetUserResponse
	4, // 9: podoai_consumer.ConsumerService.UpdateUser:output_type -> podoai_consumer.UpdateUserResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_consumer_podoai_consumer_proto_init() }
func file_consumer_podoai_consumer_proto_init() {
	if File_consumer_podoai_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consumer_podoai_consumer_proto_rawDesc), len(file_consumer_podoai_consumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consumer_podoai_consumer_proto_goTypes,
		DependencyIndexes: file_consumer_podoai_consumer_proto_depIdxs,
		MessageInfos:      file_consumer_podoai_consumer_proto_msgTypes,
	}.Build()
	File_consumer_podoai_consumer_proto = out.File
	file_consumer_podoai_consumer_proto_goTypes = nil
	file_consumer_podoai_consumer_proto_depIdxs = nil
}
