// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: clinical/podoai_clinical.proto

package clinical

import (
	common "github.com/therehabstreet/podoai/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Clinic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clinic) Reset() {
	*x = Clinic{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clinic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clinic) ProtoMessage() {}

func (x *Clinic) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clinic.ProtoReflect.Descriptor instead.
func (*Clinic) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{0}
}

func (x *Clinic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Clinic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Clinic) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ClinicUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Roles         []common.Role          `protobuf:"varint,3,rep,packed,name=roles,proto3,enum=podoai.Role" json:"roles,omitempty"`
	ClinicId      string                 `protobuf:"bytes,4,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClinicUser) Reset() {
	*x = ClinicUser{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicUser) ProtoMessage() {}

func (x *ClinicUser) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicUser.ProtoReflect.Descriptor instead.
func (*ClinicUser) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{1}
}

func (x *ClinicUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClinicUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClinicUser) GetRoles() []common.Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ClinicUser) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *ClinicUser) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ClinicUser) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetPatientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // "asc" or "desc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientsRequest) Reset() {
	*x = GetPatientsRequest{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientsRequest) ProtoMessage() {}

func (x *GetPatientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientsRequest.ProtoReflect.Descriptor instead.
func (*GetPatientsRequest) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{2}
}

func (x *GetPatientsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPatientsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPatientsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetPatientsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type GetPatientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*common.Patient      `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientsResponse) Reset() {
	*x = GetPatientsResponse{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientsResponse) ProtoMessage() {}

func (x *GetPatientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientsResponse.ProtoReflect.Descriptor instead.
func (*GetPatientsResponse) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{3}
}

func (x *GetPatientsResponse) GetPatients() []*common.Patient {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *GetPatientsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientRequest) Reset() {
	*x = GetPatientRequest{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientRequest) ProtoMessage() {}

func (x *GetPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientRequest.ProtoReflect.Descriptor instead.
func (*GetPatientRequest) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{4}
}

func (x *GetPatientRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type GetPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *common.Patient        `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientResponse) Reset() {
	*x = GetPatientResponse{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientResponse) ProtoMessage() {}

func (x *GetPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientResponse.ProtoReflect.Descriptor instead.
func (*GetPatientResponse) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{5}
}

func (x *GetPatientResponse) GetPatient() *common.Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

type SearchPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchTerm    string                 `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPatientRequest) Reset() {
	*x = SearchPatientRequest{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPatientRequest) ProtoMessage() {}

func (x *SearchPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPatientRequest.ProtoReflect.Descriptor instead.
func (*SearchPatientRequest) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{6}
}

func (x *SearchPatientRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

func (x *SearchPatientRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchPatientRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*common.Patient      `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPatientResponse) Reset() {
	*x = SearchPatientResponse{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPatientResponse) ProtoMessage() {}

func (x *SearchPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPatientResponse.ProtoReflect.Descriptor instead.
func (*SearchPatientResponse) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{7}
}

func (x *SearchPatientResponse) GetPatients() []*common.Patient {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *SearchPatientResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreatePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *common.Patient        `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePatientRequest) Reset() {
	*x = CreatePatientRequest{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePatientRequest) ProtoMessage() {}

func (x *CreatePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePatientRequest.ProtoReflect.Descriptor instead.
func (*CreatePatientRequest) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePatientRequest) GetPatient() *common.Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

type CreatePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *common.Patient        `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePatientResponse) Reset() {
	*x = CreatePatientResponse{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePatientResponse) ProtoMessage() {}

func (x *CreatePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePatientResponse.ProtoReflect.Descriptor instead.
func (*CreatePatientResponse) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePatientResponse) GetPatient() *common.Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

type DeletePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePatientRequest) Reset() {
	*x = DeletePatientRequest{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePatientRequest) ProtoMessage() {}

func (x *DeletePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePatientRequest.ProtoReflect.Descriptor instead.
func (*DeletePatientRequest) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePatientRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type DeletePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePatientResponse) Reset() {
	*x = DeletePatientResponse{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePatientResponse) ProtoMessage() {}

func (x *DeletePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePatientResponse.ProtoReflect.Descriptor instead.
func (*DeletePatientResponse) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePatientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Clinic API messages
type GetClinicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClinicId      string                 `protobuf:"bytes,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClinicRequest) Reset() {
	*x = GetClinicRequest{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClinicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClinicRequest) ProtoMessage() {}

func (x *GetClinicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClinicRequest.ProtoReflect.Descriptor instead.
func (*GetClinicRequest) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{12}
}

func (x *GetClinicRequest) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

type GetClinicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clinic        *Clinic                `protobuf:"bytes,1,opt,name=clinic,proto3" json:"clinic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClinicResponse) Reset() {
	*x = GetClinicResponse{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClinicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClinicResponse) ProtoMessage() {}

func (x *GetClinicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClinicResponse.ProtoReflect.Descriptor instead.
func (*GetClinicResponse) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{13}
}

func (x *GetClinicResponse) GetClinic() *Clinic {
	if x != nil {
		return x.Clinic
	}
	return nil
}

// ClinicUser CRUDL messages
type CreateClinicUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ClinicUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClinicUserRequest) Reset() {
	*x = CreateClinicUserRequest{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClinicUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClinicUserRequest) ProtoMessage() {}

func (x *CreateClinicUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClinicUserRequest.ProtoReflect.Descriptor instead.
func (*CreateClinicUserRequest) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{14}
}

func (x *CreateClinicUserRequest) GetUser() *ClinicUser {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateClinicUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ClinicUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClinicUserResponse) Reset() {
	*x = CreateClinicUserResponse{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClinicUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClinicUserResponse) ProtoMessage() {}

func (x *CreateClinicUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClinicUserResponse.ProtoReflect.Descriptor instead.
func (*CreateClinicUserResponse) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{15}
}

func (x *CreateClinicUserResponse) GetUser() *ClinicUser {
	if x != nil {
		return x.User
	}
	return nil
}

type GetClinicUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClinicUserRequest) Reset() {
	*x = GetClinicUserRequest{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClinicUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClinicUserRequest) ProtoMessage() {}

func (x *GetClinicUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClinicUserRequest.ProtoReflect.Descriptor instead.
func (*GetClinicUserRequest) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{16}
}

func (x *GetClinicUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetClinicUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ClinicUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClinicUserResponse) Reset() {
	*x = GetClinicUserResponse{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClinicUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClinicUserResponse) ProtoMessage() {}

func (x *GetClinicUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClinicUserResponse.ProtoReflect.Descriptor instead.
func (*GetClinicUserResponse) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{17}
}

func (x *GetClinicUserResponse) GetUser() *ClinicUser {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateClinicUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ClinicUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClinicUserRequest) Reset() {
	*x = UpdateClinicUserRequest{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClinicUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClinicUserRequest) ProtoMessage() {}

func (x *UpdateClinicUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClinicUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateClinicUserRequest) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateClinicUserRequest) GetUser() *ClinicUser {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateClinicUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ClinicUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClinicUserResponse) Reset() {
	*x = UpdateClinicUserResponse{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClinicUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClinicUserResponse) ProtoMessage() {}

func (x *UpdateClinicUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClinicUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateClinicUserResponse) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateClinicUserResponse) GetUser() *ClinicUser {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteClinicUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClinicUserRequest) Reset() {
	*x = DeleteClinicUserRequest{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClinicUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClinicUserRequest) ProtoMessage() {}

func (x *DeleteClinicUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClinicUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteClinicUserRequest) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteClinicUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteClinicUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClinicUserResponse) Reset() {
	*x = DeleteClinicUserResponse{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClinicUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClinicUserResponse) ProtoMessage() {}

func (x *DeleteClinicUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClinicUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteClinicUserResponse) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteClinicUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListClinicUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClinicId      string                 `protobuf:"bytes,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClinicUsersRequest) Reset() {
	*x = ListClinicUsersRequest{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClinicUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClinicUsersRequest) ProtoMessage() {}

func (x *ListClinicUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClinicUsersRequest.ProtoReflect.Descriptor instead.
func (*ListClinicUsersRequest) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{22}
}

func (x *ListClinicUsersRequest) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *ListClinicUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListClinicUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListClinicUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*ClinicUser          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClinicUsersResponse) Reset() {
	*x = ListClinicUsersResponse{}
	mi := &file_clinical_podoai_clinical_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClinicUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClinicUsersResponse) ProtoMessage() {}

func (x *ListClinicUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinical_podoai_clinical_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClinicUsersResponse.ProtoReflect.Descriptor instead.
func (*ListClinicUsersResponse) Descriptor() ([]byte, []int) {
	return file_clinical_podoai_clinical_proto_rawDescGZIP(), []int{23}
}

func (x *ListClinicUsersResponse) GetUsers() []*ClinicUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListClinicUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_clinical_podoai_clinical_proto protoreflect.FileDescriptor

const file_clinical_podoai_clinical_proto_rawDesc = "" +
	"\n" +
	"\x1eclinical/podoai_clinical.proto\x12\x0fpodoai_clinical\x1a\x13common/podoai.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\x06Clinic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\xe7\x01\n" +
	"\n" +
	"ClinicUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\x05roles\x18\x03 \x03(\x0e2\f.podoai.RoleR\x05roles\x12\x1b\n" +
	"\tclinic_id\x18\x04 \x01(\tR\bclinicId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"}\n" +
	"\x12GetPatientsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\"c\n" +
	"\x13GetPatientsResponse\x12+\n" +
	"\bpatients\x18\x01 \x03(\v2\x0f.podoai.PatientR\bpatients\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"2\n" +
	"\x11GetPatientRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\"?\n" +
	"\x12GetPatientResponse\x12)\n" +
	"\apatient\x18\x01 \x01(\v2\x0f.podoai.PatientR\apatient\"h\n" +
	"\x14SearchPatientRequest\x12\x1f\n" +
	"\vsearch_term\x18\x01 \x01(\tR\n" +
	"searchTerm\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"e\n" +
	"\x15SearchPatientResponse\x12+\n" +
	"\bpatients\x18\x01 \x03(\v2\x0f.podoai.PatientR\bpatients\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"A\n" +
	"\x14CreatePatientRequest\x12)\n" +
	"\apatient\x18\x01 \x01(\v2\x0f.podoai.PatientR\apatient\"B\n" +
	"\x15CreatePatientResponse\x12)\n" +
	"\apatient\x18\x01 \x01(\v2\x0f.podoai.PatientR\apatient\"5\n" +
	"\x14DeletePatientRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\"1\n" +
	"\x15DeletePatientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x10GetClinicRequest\x12\x1b\n" +
	"\tclinic_id\x18\x01 \x01(\tR\bclinicId\"D\n" +
	"\x11GetClinicResponse\x12/\n" +
	"\x06clinic\x18\x01 \x01(\v2\x17.podoai_clinical.ClinicR\x06clinic\"J\n" +
	"\x17CreateClinicUserRequest\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.podoai_clinical.ClinicUserR\x04user\"K\n" +
	"\x18CreateClinicUserResponse\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.podoai_clinical.ClinicUserR\x04user\"/\n" +
	"\x14GetClinicUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\x15GetClinicUserResponse\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.podoai_clinical.ClinicUserR\x04user\"J\n" +
	"\x17UpdateClinicUserRequest\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.podoai_clinical.ClinicUserR\x04user\"K\n" +
	"\x18UpdateClinicUserResponse\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.podoai_clinical.ClinicUserR\x04user\"2\n" +
	"\x17DeleteClinicUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"4\n" +
	"\x18DeleteClinicUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"f\n" +
	"\x16ListClinicUsersRequest\x12\x1b\n" +
	"\tclinic_id\x18\x01 \x01(\tR\bclinicId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"m\n" +
	"\x17ListClinicUsersResponse\x121\n" +
	"\x05users\x18\x01 \x03(\v2\x1b.podoai_clinical.ClinicUserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\xb7\b\n" +
	"\x0fClinicalService\x12X\n" +
	"\vGetPatients\x12#.podoai_clinical.GetPatientsRequest\x1a$.podoai_clinical.GetPatientsResponse\x12U\n" +
	"\n" +
	"GetPatient\x12\".podoai_clinical.GetPatientRequest\x1a#.podoai_clinical.GetPatientResponse\x12^\n" +
	"\rSearchPatient\x12%.podoai_clinical.SearchPatientRequest\x1a&.podoai_clinical.SearchPatientResponse\x12^\n" +
	"\rCreatePatient\x12%.podoai_clinical.CreatePatientRequest\x1a&.podoai_clinical.CreatePatientResponse\x12^\n" +
	"\rDeletePatient\x12%.podoai_clinical.DeletePatientRequest\x1a&.podoai_clinical.DeletePatientResponse\x12R\n" +
	"\tGetClinic\x12!.podoai_clinical.GetClinicRequest\x1a\".podoai_clinical.GetClinicResponse\x12g\n" +
	"\x10CreateClinicUser\x12(.podoai_clinical.CreateClinicUserRequest\x1a).podoai_clinical.CreateClinicUserResponse\x12^\n" +
	"\rGetClinicUser\x12%.podoai_clinical.GetClinicUserRequest\x1a&.podoai_clinical.GetClinicUserResponse\x12g\n" +
	"\x10UpdateClinicUser\x12(.podoai_clinical.UpdateClinicUserRequest\x1a).podoai_clinical.UpdateClinicUserResponse\x12g\n" +
	"\x10DeleteClinicUser\x12(.podoai_clinical.DeleteClinicUserRequest\x1a).podoai_clinical.DeleteClinicUserResponse\x12d\n" +
	"\x0fListClinicUsers\x12'.podoai_clinical.ListClinicUsersRequest\x1a(.podoai_clinical.ListClinicUsersResponseB1Z/github.com/therehabstreet/podoai/proto/clinicalb\x06proto3"

var (
	file_clinical_podoai_clinical_proto_rawDescOnce sync.Once
	file_clinical_podoai_clinical_proto_rawDescData []byte
)

func file_clinical_podoai_clinical_proto_rawDescGZIP() []byte {
	file_clinical_podoai_clinical_proto_rawDescOnce.Do(func() {
		file_clinical_podoai_clinical_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clinical_podoai_clinical_proto_rawDesc), len(file_clinical_podoai_clinical_proto_rawDesc)))
	})
	return file_clinical_podoai_clinical_proto_rawDescData
}

var file_clinical_podoai_clinical_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_clinical_podoai_clinical_proto_goTypes = []any{
	(*Clinic)(nil),                   // 0: podoai_clinical.Clinic
	(*ClinicUser)(nil),               // 1: podoai_clinical.ClinicUser
	(*GetPatientsRequest)(nil),       // 2: podoai_clinical.GetPatientsRequest
	(*GetPatientsResponse)(nil),      // 3: podoai_clinical.GetPatientsResponse
	(*GetPatientRequest)(nil),        // 4: podoai_clinical.GetPatientRequest
	(*GetPatientResponse)(nil),       // 5: podoai_clinical.GetPatientResponse
	(*SearchPatientRequest)(nil),     // 6: podoai_clinical.SearchPatientRequest
	(*SearchPatientResponse)(nil),    // 7: podoai_clinical.SearchPatientResponse
	(*CreatePatientRequest)(nil),     // 8: podoai_clinical.CreatePatientRequest
	(*CreatePatientResponse)(nil),    // 9: podoai_clinical.CreatePatientResponse
	(*DeletePatientRequest)(nil),     // 10: podoai_clinical.DeletePatientRequest
	(*DeletePatientResponse)(nil),    // 11: podoai_clinical.DeletePatientResponse
	(*GetClinicRequest)(nil),         // 12: podoai_clinical.GetClinicRequest
	(*GetClinicResponse)(nil),        // 13: podoai_clinical.GetClinicResponse
	(*CreateClinicUserRequest)(nil),  // 14: podoai_clinical.CreateClinicUserRequest
	(*CreateClinicUserResponse)(nil), // 15: podoai_clinical.CreateClinicUserResponse
	(*GetClinicUserRequest)(nil),     // 16: podoai_clinical.GetClinicUserRequest
	(*GetClinicUserResponse)(nil),    // 17: podoai_clinical.GetClinicUserResponse
	(*UpdateClinicUserRequest)(nil),  // 18: podoai_clinical.UpdateClinicUserRequest
	(*UpdateClinicUserResponse)(nil), // 19: podoai_clinical.UpdateClinicUserResponse
	(*DeleteClinicUserRequest)(nil),  // 20: podoai_clinical.DeleteClinicUserRequest
	(*DeleteClinicUserResponse)(nil), // 21: podoai_clinical.DeleteClinicUserResponse
	(*ListClinicUsersRequest)(nil),   // 22: podoai_clinical.ListClinicUsersRequest
	(*ListClinicUsersResponse)(nil),  // 23: podoai_clinical.ListClinicUsersResponse
	(common.Role)(0),                 // 24: podoai.Role
	(*timestamppb.Timestamp)(nil),    // 25: google.protobuf.Timestamp
	(*common.Patient)(nil),           // 26: podoai.Patient
}
var file_clinical_podoai_clinical_proto_depIdxs = []int32{
	24, // 0: podoai_clinical.ClinicUser.roles:type_name -> podoai.Role
	25, // 1: podoai_clinical.ClinicUser.created_at:type_name -> google.protobuf.Timestamp
	25, // 2: podoai_clinical.ClinicUser.updated_at:type_name -> google.protobuf.Timestamp
	26, // 3: podoai_clinical.GetPatientsResponse.patients:type_name -> podoai.Patient
	26, // 4: podoai_clinical.GetPatientResponse.patient:type_name -> podoai.Patient
	26, // 5: podoai_clinical.SearchPatientResponse.patients:type_name -> podoai.Patient
	26, // 6: podoai_clinical.CreatePatientRequest.patient:type_name -> podoai.Patient
	26, // 7: podoai_clinical.CreatePatientResponse.patient:type_name -> podoai.Patient
	0,  // 8: podoai_clinical.GetClinicResponse.clinic:type_name -> podoai_clinical.Clinic
	1,  // 9: podoai_clinical.CreateClinicUserRequest.user:type_name -> podoai_clinical.ClinicUser
	1,  // 10: podoai_clinical.CreateClinicUserResponse.user:type_name -> podoai_clinical.ClinicUser
	1,  // 11: podoai_clinical.GetClinicUserResponse.user:type_name -> podoai_clinical.ClinicUser
	1,  // 12: podoai_clinical.UpdateClinicUserRequest.user:type_name -> podoai_clinical.ClinicUser
	1,  // 13: podoai_clinical.UpdateClinicUserResponse.user:type_name -> podoai_clinical.ClinicUser
	1,  // 14: podoai_clinical.ListClinicUsersResponse.users:type_name -> podoai_clinical.ClinicUser
	2,  // 15: podoai_clinical.ClinicalService.GetPatients:input_type -> podoai_clinical.GetPatientsRequest
	4,  // 16: podoai_clinical.ClinicalService.GetPatient:input_type -> podoai_clinical.GetPatientRequest
	6,  // 17: podoai_clinical.ClinicalService.SearchPatient:input_type -> podoai_clinical.SearchPatientRequest
	8,  // 18: podoai_clinical.ClinicalService.CreatePatient:input_type -> podoai_clinical.CreatePatientRequest
	10, // 19: podoai_clinical.ClinicalService.DeletePatient:input_type -> podoai_clinical.DeletePatientRequest
	12, // 20: podoai_clinical.ClinicalService.GetClinic:input_type -> podoai_clinical.GetClinicRequest
	14, // 21: podoai_clinical.ClinicalService.CreateClinicUser:input_type -> podoai_clinical.CreateClinicUserRequest
	16, // 22: podoai_clinical.ClinicalService.GetClinicUser:input_type -> podoai_clinical.GetClinicUserRequest
	18, // 23: podoai_clinical.ClinicalService.UpdateClinicUser:input_type -> podoai_clinical.UpdateClinicUserRequest
	20, // 24: podoai_clinical.ClinicalService.DeleteClinicUser:input_type -> podoai_clinical.DeleteClinicUserRequest
	22, // 25: podoai_clinical.ClinicalService.ListClinicUsers:input_type -> podoai_clinical.ListClinicUsersRequest
	3,  // 26: podoai_clinical.ClinicalService.GetPatients:output_type -> podoai_clinical.GetPatientsResponse
	5,  // 27: podoai_clinical.ClinicalService.GetPatient:output_type -> podoai_clinical.GetPatientResponse
	7,  // 28: podoai_clinical.ClinicalService.SearchPatient:output_type -> podoai_clinical.SearchPatientResponse
	9,  // 29: podoai_clinical.ClinicalService.CreatePatient:output_type -> podoai_clinical.CreatePatientResponse
	11, // 30: podoai_clinical.ClinicalService.DeletePatient:output_type -> podoai_clinical.DeletePatientResponse
	13, // 31: podoai_clinical.ClinicalService.GetClinic:output_type -> podoai_clinical.GetClinicResponse
	15, // 32: podoai_clinical.ClinicalService.CreateClinicUser:output_type -> podoai_clinical.CreateClinicUserResponse
	17, // 33: podoai_clinical.ClinicalService.GetClinicUser:output_type -> podoai_clinical.GetClinicUserResponse
	19, // 34: podoai_clinical.ClinicalService.UpdateClinicUser:output_type -> podoai_clinical.UpdateClinicUserResponse
	21, // 35: podoai_clinical.ClinicalService.DeleteClinicUser:output_type -> podoai_clinical.DeleteClinicUserResponse
	23, // 36: podoai_clinical.ClinicalService.ListClinicUsers:output_type -> podoai_clinical.ListClinicUsersResponse
	26, // [26:37] is the sub-list for method output_type
	15, // [15:26] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_clinical_podoai_clinical_proto_init() }
func file_clinical_podoai_clinical_proto_init() {
	if File_clinical_podoai_clinical_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clinical_podoai_clinical_proto_rawDesc), len(file_clinical_podoai_clinical_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clinical_podoai_clinical_proto_goTypes,
		DependencyIndexes: file_clinical_podoai_clinical_proto_depIdxs,
		MessageInfos:      file_clinical_podoai_clinical_proto_msgTypes,
	}.Build()
	File_clinical_podoai_clinical_proto = out.File
	file_clinical_podoai_clinical_proto_goTypes = nil
	file_clinical_podoai_clinical_proto_depIdxs = nil
}
