// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: common/podoai.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED   Role = 0
	Role_SUPERADMIN         Role = 1
	Role_ADMIN              Role = 2
	Role_CLINIC_CHAIN_ADMIN Role = 3
	Role_CLINIC_ADMIN       Role = 4
	Role_CLINIC_STAFF       Role = 5
	Role_CONSUMER           Role = 6
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "SUPERADMIN",
		2: "ADMIN",
		3: "CLINIC_CHAIN_ADMIN",
		4: "CLINIC_ADMIN",
		5: "CLINIC_STAFF",
		6: "CONSUMER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED":   0,
		"SUPERADMIN":         1,
		"ADMIN":              2,
		"CLINIC_CHAIN_ADMIN": 3,
		"CLINIC_ADMIN":       4,
		"CLINIC_STAFF":       5,
		"CONSUMER":           6,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_common_podoai_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_common_podoai_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{0}
}

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_MALE               Gender = 1
	Gender_FEMALE             Gender = 2
	Gender_OTHER              Gender = 3
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "MALE",
		2: "FEMALE",
		3: "OTHER",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"MALE":               1,
		"FEMALE":             2,
		"OTHER":              3,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_common_podoai_proto_enumTypes[1].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_common_podoai_proto_enumTypes[1]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{1}
}

type Scan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClinicId      string                 `protobuf:"bytes,3,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Images        []*Image               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Videos        []*Video               `protobuf:"bytes,6,rep,name=videos,proto3" json:"videos,omitempty"`
	ScanAiResult  *ScanAIResult          `protobuf:"bytes,7,opt,name=scan_ai_result,json=scanAiResult,proto3" json:"scan_ai_result,omitempty"`
	ScannedById   string                 `protobuf:"bytes,8,opt,name=scanned_by_id,json=scannedById,proto3" json:"scanned_by_id,omitempty"`
	ReviewedById  string                 `protobuf:"bytes,9,opt,name=reviewed_by_id,json=reviewedById,proto3" json:"reviewed_by_id,omitempty"`
	ReviewedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=reviewed_at,json=reviewedAt,proto3" json:"reviewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scan) Reset() {
	*x = Scan{}
	mi := &file_common_podoai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scan) ProtoMessage() {}

func (x *Scan) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scan.ProtoReflect.Descriptor instead.
func (*Scan) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{0}
}

func (x *Scan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Scan) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Scan) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *Scan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Scan) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Scan) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *Scan) GetScanAiResult() *ScanAIResult {
	if x != nil {
		return x.ScanAiResult
	}
	return nil
}

func (x *Scan) GetScannedById() string {
	if x != nil {
		return x.ScannedById
	}
	return ""
}

func (x *Scan) GetReviewedById() string {
	if x != nil {
		return x.ReviewedById
	}
	return ""
}

func (x *Scan) GetReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReviewedAt
	}
	return nil
}

type ScanAIResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ArchType       string                 `protobuf:"bytes,1,opt,name=arch_type,json=archType,proto3" json:"arch_type,omitempty"`
	Pronation      string                 `protobuf:"bytes,2,opt,name=pronation,proto3" json:"pronation,omitempty"`
	BalanceScore   float32                `protobuf:"fixed32,3,opt,name=balance_score,json=balanceScore,proto3" json:"balance_score,omitempty"`
	LlmResult      *ScanLLMResult         `protobuf:"bytes,4,opt,name=llm_result,json=llmResult,proto3" json:"llm_result,omitempty"`
	Recommendation *ScanRecommendation    `protobuf:"bytes,5,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScanAIResult) Reset() {
	*x = ScanAIResult{}
	mi := &file_common_podoai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanAIResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanAIResult) ProtoMessage() {}

func (x *ScanAIResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanAIResult.ProtoReflect.Descriptor instead.
func (*ScanAIResult) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{1}
}

func (x *ScanAIResult) GetArchType() string {
	if x != nil {
		return x.ArchType
	}
	return ""
}

func (x *ScanAIResult) GetPronation() string {
	if x != nil {
		return x.Pronation
	}
	return ""
}

func (x *ScanAIResult) GetBalanceScore() float32 {
	if x != nil {
		return x.BalanceScore
	}
	return 0
}

func (x *ScanAIResult) GetLlmResult() *ScanLLMResult {
	if x != nil {
		return x.LlmResult
	}
	return nil
}

func (x *ScanAIResult) GetRecommendation() *ScanRecommendation {
	if x != nil {
		return x.Recommendation
	}
	return nil
}

type ScanLLMResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanLLMResult) Reset() {
	*x = ScanLLMResult{}
	mi := &file_common_podoai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanLLMResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanLLMResult) ProtoMessage() {}

func (x *ScanLLMResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanLLMResult.ProtoReflect.Descriptor instead.
func (*ScanLLMResult) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{2}
}

func (x *ScanLLMResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ScanRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Exercises     []*Exercise            `protobuf:"bytes,2,rep,name=exercises,proto3" json:"exercises,omitempty"`
	Therapies     []*Therapy             `protobuf:"bytes,3,rep,name=therapies,proto3" json:"therapies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRecommendation) Reset() {
	*x = ScanRecommendation{}
	mi := &file_common_podoai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRecommendation) ProtoMessage() {}

func (x *ScanRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRecommendation.ProtoReflect.Descriptor instead.
func (*ScanRecommendation) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{3}
}

func (x *ScanRecommendation) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ScanRecommendation) GetExercises() []*Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

func (x *ScanRecommendation) GetTherapies() []*Therapy {
	if x != nil {
		return x.Therapies
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,4,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	Category      *ProductCategory       `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Prices        []*ProductPrice        `protobuf:"bytes,6,rep,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_common_podoai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{4}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *Product) GetCategory() *ProductCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Product) GetPrices() []*ProductPrice {
	if x != nil {
		return x.Prices
	}
	return nil
}

type ProductCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCategory) Reset() {
	*x = ProductCategory{}
	mi := &file_common_podoai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCategory) ProtoMessage() {}

func (x *ProductCategory) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCategory.ProtoReflect.Descriptor instead.
func (*ProductCategory) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{5}
}

func (x *ProductCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductCategory) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type ProductPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductPrice) Reset() {
	*x = ProductPrice{}
	mi := &file_common_podoai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPrice) ProtoMessage() {}

func (x *ProductPrice) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPrice.ProtoReflect.Descriptor instead.
func (*ProductPrice) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{6}
}

func (x *ProductPrice) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductPrice) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductPrice) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Exercise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	mi := &file_common_podoai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{7}
}

func (x *Exercise) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Exercise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exercise) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Exercise) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type Therapy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Therapy) Reset() {
	*x = Therapy{}
	mi := &file_common_podoai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Therapy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Therapy) ProtoMessage() {}

func (x *Therapy) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Therapy.ProtoReflect.Descriptor instead.
func (*Therapy) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{8}
}

func (x *Therapy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Therapy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Therapy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Therapy) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // left_foot_top, right_foot_side, etc
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	CapturedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_common_podoai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{9}
}

func (x *Image) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // rear_walk, front_walk, side_walk, etc
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	CapturedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_common_podoai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{10}
}

func (x *Video) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Video) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Video) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Video) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

type Patient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	OwnerEntityId string                 `protobuf:"bytes,4,opt,name=owner_entity_id,json=ownerEntityId,proto3" json:"owner_entity_id,omitempty"`
	Age           int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Gender        Gender                 `protobuf:"varint,6,opt,name=gender,proto3,enum=podoai.Gender" json:"gender,omitempty"`
	FootSize      int32                  `protobuf:"varint,7,opt,name=foot_size,json=footSize,proto3" json:"foot_size,omitempty"`
	TotalScans    int32                  `protobuf:"varint,8,opt,name=total_scans,json=totalScans,proto3" json:"total_scans,omitempty"`
	LastScanDate  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_scan_date,json=lastScanDate,proto3" json:"last_scan_date,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Patient) Reset() {
	*x = Patient{}
	mi := &file_common_podoai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient) ProtoMessage() {}

func (x *Patient) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient.ProtoReflect.Descriptor instead.
func (*Patient) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{11}
}

func (x *Patient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Patient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Patient) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Patient) GetOwnerEntityId() string {
	if x != nil {
		return x.OwnerEntityId
	}
	return ""
}

func (x *Patient) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Patient) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *Patient) GetFootSize() int32 {
	if x != nil {
		return x.FootSize
	}
	return 0
}

func (x *Patient) GetTotalScans() int32 {
	if x != nil {
		return x.TotalScans
	}
	return 0
}

func (x *Patient) GetLastScanDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastScanDate
	}
	return nil
}

func (x *Patient) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetScansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // "asc" or "desc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScansRequest) Reset() {
	*x = GetScansRequest{}
	mi := &file_common_podoai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScansRequest) ProtoMessage() {}

func (x *GetScansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScansRequest.ProtoReflect.Descriptor instead.
func (*GetScansRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{12}
}

func (x *GetScansRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetScansRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetScansRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetScansRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetScansRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type GetScansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scans         []*Scan                `protobuf:"bytes,1,rep,name=scans,proto3" json:"scans,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScansResponse) Reset() {
	*x = GetScansResponse{}
	mi := &file_common_podoai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScansResponse) ProtoMessage() {}

func (x *GetScansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScansResponse.ProtoReflect.Descriptor instead.
func (*GetScansResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{13}
}

func (x *GetScansResponse) GetScans() []*Scan {
	if x != nil {
		return x.Scans
	}
	return nil
}

func (x *GetScansResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanRequest) Reset() {
	*x = GetScanRequest{}
	mi := &file_common_podoai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanRequest) ProtoMessage() {}

func (x *GetScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanRequest.ProtoReflect.Descriptor instead.
func (*GetScanRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{14}
}

func (x *GetScanRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type GetScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scan          *Scan                  `protobuf:"bytes,1,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanResponse) Reset() {
	*x = GetScanResponse{}
	mi := &file_common_podoai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanResponse) ProtoMessage() {}

func (x *GetScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanResponse.ProtoReflect.Descriptor instead.
func (*GetScanResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{15}
}

func (x *GetScanResponse) GetScan() *Scan {
	if x != nil {
		return x.Scan
	}
	return nil
}

type CreateScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scan          *Scan                  `protobuf:"bytes,1,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScanRequest) Reset() {
	*x = CreateScanRequest{}
	mi := &file_common_podoai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScanRequest) ProtoMessage() {}

func (x *CreateScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScanRequest.ProtoReflect.Descriptor instead.
func (*CreateScanRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{16}
}

func (x *CreateScanRequest) GetScan() *Scan {
	if x != nil {
		return x.Scan
	}
	return nil
}

type CreateScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scan          *Scan                  `protobuf:"bytes,1,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScanResponse) Reset() {
	*x = CreateScanResponse{}
	mi := &file_common_podoai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScanResponse) ProtoMessage() {}

func (x *CreateScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScanResponse.ProtoReflect.Descriptor instead.
func (*CreateScanResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{17}
}

func (x *CreateScanResponse) GetScan() *Scan {
	if x != nil {
		return x.Scan
	}
	return nil
}

type DeleteScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScanRequest) Reset() {
	*x = DeleteScanRequest{}
	mi := &file_common_podoai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScanRequest) ProtoMessage() {}

func (x *DeleteScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScanRequest.ProtoReflect.Descriptor instead.
func (*DeleteScanRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteScanRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type DeleteScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScanResponse) Reset() {
	*x = DeleteScanResponse{}
	mi := &file_common_podoai_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScanResponse) ProtoMessage() {}

func (x *DeleteScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScanResponse.ProtoReflect.Descriptor instead.
func (*DeleteScanResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteScanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_common_podoai_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{20}
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_common_podoai_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{21}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseRequest) Reset() {
	*x = GetExerciseRequest{}
	mi := &file_common_podoai_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseRequest) ProtoMessage() {}

func (x *GetExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseRequest.ProtoReflect.Descriptor instead.
func (*GetExerciseRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{22}
}

func (x *GetExerciseRequest) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

type GetExerciseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercise      *Exercise              `protobuf:"bytes,1,opt,name=exercise,proto3" json:"exercise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseResponse) Reset() {
	*x = GetExerciseResponse{}
	mi := &file_common_podoai_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseResponse) ProtoMessage() {}

func (x *GetExerciseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseResponse.ProtoReflect.Descriptor instead.
func (*GetExerciseResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{23}
}

func (x *GetExerciseResponse) GetExercise() *Exercise {
	if x != nil {
		return x.Exercise
	}
	return nil
}

type GetTherapyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapyId     string                 `protobuf:"bytes,1,opt,name=therapy_id,json=therapyId,proto3" json:"therapy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTherapyRequest) Reset() {
	*x = GetTherapyRequest{}
	mi := &file_common_podoai_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTherapyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTherapyRequest) ProtoMessage() {}

func (x *GetTherapyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTherapyRequest.ProtoReflect.Descriptor instead.
func (*GetTherapyRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{24}
}

func (x *GetTherapyRequest) GetTherapyId() string {
	if x != nil {
		return x.TherapyId
	}
	return ""
}

type GetTherapyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Therapy       *Therapy               `protobuf:"bytes,1,opt,name=therapy,proto3" json:"therapy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTherapyResponse) Reset() {
	*x = GetTherapyResponse{}
	mi := &file_common_podoai_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTherapyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTherapyResponse) ProtoMessage() {}

func (x *GetTherapyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTherapyResponse.ProtoReflect.Descriptor instead.
func (*GetTherapyResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{25}
}

func (x *GetTherapyResponse) GetTherapy() *Therapy {
	if x != nil {
		return x.Therapy
	}
	return nil
}

// ===== Authentication =====
type RequestOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MobileNumber  string                 `protobuf:"bytes,1,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOtpRequest) Reset() {
	*x = RequestOtpRequest{}
	mi := &file_common_podoai_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOtpRequest) ProtoMessage() {}

func (x *RequestOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOtpRequest.ProtoReflect.Descriptor instead.
func (*RequestOtpRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{26}
}

func (x *RequestOtpRequest) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

type RequestOtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOtpResponse) Reset() {
	*x = RequestOtpResponse{}
	mi := &file_common_podoai_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOtpResponse) ProtoMessage() {}

func (x *RequestOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOtpResponse.ProtoReflect.Descriptor instead.
func (*RequestOtpResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{27}
}

func (x *RequestOtpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RequestOtpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MobileNumber  string                 `protobuf:"bytes,1,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOtpRequest) Reset() {
	*x = VerifyOtpRequest{}
	mi := &file_common_podoai_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOtpRequest) ProtoMessage() {}

func (x *VerifyOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOtpRequest.ProtoReflect.Descriptor instead.
func (*VerifyOtpRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{28}
}

func (x *VerifyOtpRequest) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *VerifyOtpRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_common_podoai_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{29}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_common_podoai_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{30}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_common_podoai_proto protoreflect.FileDescriptor

const file_common_podoai_proto_rawDesc = "" +
	"\n" +
	"\x13common/podoai.proto\x12\x06podoai\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x03\n" +
	"\x04Scan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tclinic_id\x18\x03 \x01(\tR\bclinicId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12%\n" +
	"\x06images\x18\x05 \x03(\v2\r.podoai.ImageR\x06images\x12%\n" +
	"\x06videos\x18\x06 \x03(\v2\r.podoai.VideoR\x06videos\x12:\n" +
	"\x0escan_ai_result\x18\a \x01(\v2\x14.podoai.ScanAIResultR\fscanAiResult\x12\"\n" +
	"\rscanned_by_id\x18\b \x01(\tR\vscannedById\x12$\n" +
	"\x0ereviewed_by_id\x18\t \x01(\tR\freviewedById\x12;\n" +
	"\vreviewed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reviewedAt\"\xe8\x01\n" +
	"\fScanAIResult\x12\x1b\n" +
	"\tarch_type\x18\x01 \x01(\tR\barchType\x12\x1c\n" +
	"\tpronation\x18\x02 \x01(\tR\tpronation\x12#\n" +
	"\rbalance_score\x18\x03 \x01(\x02R\fbalanceScore\x124\n" +
	"\n" +
	"llm_result\x18\x04 \x01(\v2\x15.podoai.ScanLLMResultR\tllmResult\x12B\n" +
	"\x0erecommendation\x18\x05 \x01(\v2\x1a.podoai.ScanRecommendationR\x0erecommendation\")\n" +
	"\rScanLLMResult\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\"\xa0\x01\n" +
	"\x12ScanRecommendation\x12+\n" +
	"\bproducts\x18\x01 \x03(\v2\x0f.podoai.ProductR\bproducts\x12.\n" +
	"\texercises\x18\x02 \x03(\v2\x10.podoai.ExerciseR\texercises\x12-\n" +
	"\ttherapies\x18\x03 \x03(\v2\x0f.podoai.TherapyR\ttherapies\"\xd1\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x04 \x03(\tR\tmediaUrls\x123\n" +
	"\bcategory\x18\x05 \x01(\v2\x17.podoai.ProductCategoryR\bcategory\x12,\n" +
	"\x06prices\x18\x06 \x03(\v2\x14.podoai.ProductPriceR\x06prices\"t\n" +
	"\x0fProductCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\"_\n" +
	"\fProductPrice\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"m\n" +
	"\bExercise\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\"l\n" +
	"\aTherapy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\"j\n" +
	"\x05Image\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12;\n" +
	"\vcaptured_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\"\x86\x01\n" +
	"\x05Video\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12;\n" +
	"\vcaptured_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\"\xed\x02\n" +
	"\aPatient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12&\n" +
	"\x0fowner_entity_id\x18\x04 \x01(\tR\rownerEntityId\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\x12&\n" +
	"\x06gender\x18\x06 \x01(\x0e2\x0e.podoai.GenderR\x06gender\x12\x1b\n" +
	"\tfoot_size\x18\a \x01(\x05R\bfootSize\x12\x1f\n" +
	"\vtotal_scans\x18\b \x01(\x05R\n" +
	"totalScans\x12@\n" +
	"\x0elast_scan_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\flastScanDate\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x93\x01\n" +
	"\x0fGetScansRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x04 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\tR\tsortOrder\"W\n" +
	"\x10GetScansResponse\x12\"\n" +
	"\x05scans\x18\x01 \x03(\v2\f.podoai.ScanR\x05scans\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\")\n" +
	"\x0eGetScanRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\"3\n" +
	"\x0fGetScanResponse\x12 \n" +
	"\x04scan\x18\x01 \x01(\v2\f.podoai.ScanR\x04scan\"5\n" +
	"\x11CreateScanRequest\x12 \n" +
	"\x04scan\x18\x01 \x01(\v2\f.podoai.ScanR\x04scan\"6\n" +
	"\x12CreateScanResponse\x12 \n" +
	"\x04scan\x18\x01 \x01(\v2\f.podoai.ScanR\x04scan\",\n" +
	"\x11DeleteScanRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\".\n" +
	"\x12DeleteScanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"?\n" +
	"\x12GetProductResponse\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.podoai.ProductR\aproduct\"5\n" +
	"\x12GetExerciseRequest\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\"C\n" +
	"\x13GetExerciseResponse\x12,\n" +
	"\bexercise\x18\x01 \x01(\v2\x10.podoai.ExerciseR\bexercise\"2\n" +
	"\x11GetTherapyRequest\x12\x1d\n" +
	"\n" +
	"therapy_id\x18\x01 \x01(\tR\ttherapyId\"?\n" +
	"\x12GetTherapyResponse\x12)\n" +
	"\atherapy\x18\x01 \x01(\v2\x0f.podoai.TherapyR\atherapy\"8\n" +
	"\x11RequestOtpRequest\x12#\n" +
	"\rmobile_number\x18\x01 \x01(\tR\fmobileNumber\"H\n" +
	"\x12RequestOtpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x10VerifyOtpRequest\x12#\n" +
	"\rmobile_number\x18\x01 \x01(\tR\fmobileNumber\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"i\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn*\x81\x01\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"SUPERADMIN\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02\x12\x16\n" +
	"\x12CLINIC_CHAIN_ADMIN\x10\x03\x12\x10\n" +
	"\fCLINIC_ADMIN\x10\x04\x12\x10\n" +
	"\fCLINIC_STAFF\x10\x05\x12\f\n" +
	"\bCONSUMER\x10\x06*A\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04MALE\x10\x01\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x02\x12\t\n" +
	"\x05OTHER\x10\x032\x9f\x05\n" +
	"\rCommonService\x12C\n" +
	"\n" +
	"RequestOtp\x12\x19.podoai.RequestOtpRequest\x1a\x1a.podoai.RequestOtpResponse\x12<\n" +
	"\tVerifyOtp\x12\x18.podoai.VerifyOtpRequest\x1a\x15.podoai.LoginResponse\x124\n" +
	"\x05Login\x12\x14.podoai.LoginRequest\x1a\x15.podoai.LoginResponse\x12=\n" +
	"\bGetScans\x12\x17.podoai.GetScansRequest\x1a\x18.podoai.GetScansResponse\x12:\n" +
	"\aGetScan\x12\x16.podoai.GetScanRequest\x1a\x17.podoai.GetScanResponse\x12C\n" +
	"\n" +
	"CreateScan\x12\x19.podoai.CreateScanRequest\x1a\x1a.podoai.CreateScanResponse\x12C\n" +
	"\n" +
	"DeleteScan\x12\x19.podoai.DeleteScanRequest\x1a\x1a.podoai.DeleteScanResponse\x12C\n" +
	"\n" +
	"GetProduct\x12\x19.podoai.GetProductRequest\x1a\x1a.podoai.GetProductResponse\x12F\n" +
	"\vGetExercise\x12\x1a.podoai.GetExerciseRequest\x1a\x1b.podoai.GetExerciseResponse\x12C\n" +
	"\n" +
	"GetTherapy\x12\x19.podoai.GetTherapyRequest\x1a\x1a.podoai.GetTherapyResponseB/Z-github.com/therehabstreet/podoai/proto/commonb\x06proto3"

var (
	file_common_podoai_proto_rawDescOnce sync.Once
	file_common_podoai_proto_rawDescData []byte
)

func file_common_podoai_proto_rawDescGZIP() []byte {
	file_common_podoai_proto_rawDescOnce.Do(func() {
		file_common_podoai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_podoai_proto_rawDesc), len(file_common_podoai_proto_rawDesc)))
	})
	return file_common_podoai_proto_rawDescData
}

var file_common_podoai_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_podoai_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_common_podoai_proto_goTypes = []any{
	(Role)(0),                     // 0: podoai.Role
	(Gender)(0),                   // 1: podoai.Gender
	(*Scan)(nil),                  // 2: podoai.Scan
	(*ScanAIResult)(nil),          // 3: podoai.ScanAIResult
	(*ScanLLMResult)(nil),         // 4: podoai.ScanLLMResult
	(*ScanRecommendation)(nil),    // 5: podoai.ScanRecommendation
	(*Product)(nil),               // 6: podoai.Product
	(*ProductCategory)(nil),       // 7: podoai.ProductCategory
	(*ProductPrice)(nil),          // 8: podoai.ProductPrice
	(*Exercise)(nil),              // 9: podoai.Exercise
	(*Therapy)(nil),               // 10: podoai.Therapy
	(*Image)(nil),                 // 11: podoai.Image
	(*Video)(nil),                 // 12: podoai.Video
	(*Patient)(nil),               // 13: podoai.Patient
	(*GetScansRequest)(nil),       // 14: podoai.GetScansRequest
	(*GetScansResponse)(nil),      // 15: podoai.GetScansResponse
	(*GetScanRequest)(nil),        // 16: podoai.GetScanRequest
	(*GetScanResponse)(nil),       // 17: podoai.GetScanResponse
	(*CreateScanRequest)(nil),     // 18: podoai.CreateScanRequest
	(*CreateScanResponse)(nil),    // 19: podoai.CreateScanResponse
	(*DeleteScanRequest)(nil),     // 20: podoai.DeleteScanRequest
	(*DeleteScanResponse)(nil),    // 21: podoai.DeleteScanResponse
	(*GetProductRequest)(nil),     // 22: podoai.GetProductRequest
	(*GetProductResponse)(nil),    // 23: podoai.GetProductResponse
	(*GetExerciseRequest)(nil),    // 24: podoai.GetExerciseRequest
	(*GetExerciseResponse)(nil),   // 25: podoai.GetExerciseResponse
	(*GetTherapyRequest)(nil),     // 26: podoai.GetTherapyRequest
	(*GetTherapyResponse)(nil),    // 27: podoai.GetTherapyResponse
	(*RequestOtpRequest)(nil),     // 28: podoai.RequestOtpRequest
	(*RequestOtpResponse)(nil),    // 29: podoai.RequestOtpResponse
	(*VerifyOtpRequest)(nil),      // 30: podoai.VerifyOtpRequest
	(*LoginRequest)(nil),          // 31: podoai.LoginRequest
	(*LoginResponse)(nil),         // 32: podoai.LoginResponse
	(*timestamppb.Timestamp)(nil), // 33: google.protobuf.Timestamp
}
var file_common_podoai_proto_depIdxs = []int32{
	33, // 0: podoai.Scan.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: podoai.Scan.images:type_name -> podoai.Image
	12, // 2: podoai.Scan.videos:type_name -> podoai.Video
	3,  // 3: podoai.Scan.scan_ai_result:type_name -> podoai.ScanAIResult
	33, // 4: podoai.Scan.reviewed_at:type_name -> google.protobuf.Timestamp
	4,  // 5: podoai.ScanAIResult.llm_result:type_name -> podoai.ScanLLMResult
	5,  // 6: podoai.ScanAIResult.recommendation:type_name -> podoai.ScanRecommendation
	6,  // 7: podoai.ScanRecommendation.products:type_name -> podoai.Product
	9,  // 8: podoai.ScanRecommendation.exercises:type_name -> podoai.Exercise
	10, // 9: podoai.ScanRecommendation.therapies:type_name -> podoai.Therapy
	7,  // 10: podoai.Product.category:type_name -> podoai.ProductCategory
	8,  // 11: podoai.Product.prices:type_name -> podoai.ProductPrice
	33, // 12: podoai.Image.captured_at:type_name -> google.protobuf.Timestamp
	33, // 13: podoai.Video.captured_at:type_name -> google.protobuf.Timestamp
	1,  // 14: podoai.Patient.gender:type_name -> podoai.Gender
	33, // 15: podoai.Patient.last_scan_date:type_name -> google.protobuf.Timestamp
	33, // 16: podoai.Patient.created_at:type_name -> google.protobuf.Timestamp
	2,  // 17: podoai.GetScansResponse.scans:type_name -> podoai.Scan
	2,  // 18: podoai.GetScanResponse.scan:type_name -> podoai.Scan
	2,  // 19: podoai.CreateScanRequest.scan:type_name -> podoai.Scan
	2,  // 20: podoai.CreateScanResponse.scan:type_name -> podoai.Scan
	6,  // 21: podoai.GetProductResponse.product:type_name -> podoai.Product
	9,  // 22: podoai.GetExerciseResponse.exercise:type_name -> podoai.Exercise
	10, // 23: podoai.GetTherapyResponse.therapy:type_name -> podoai.Therapy
	28, // 24: podoai.CommonService.RequestOtp:input_type -> podoai.RequestOtpRequest
	30, // 25: podoai.CommonService.VerifyOtp:input_type -> podoai.VerifyOtpRequest
	31, // 26: podoai.CommonService.Login:input_type -> podoai.LoginRequest
	14, // 27: podoai.CommonService.GetScans:input_type -> podoai.GetScansRequest
	16, // 28: podoai.CommonService.GetScan:input_type -> podoai.GetScanRequest
	18, // 29: podoai.CommonService.CreateScan:input_type -> podoai.CreateScanRequest
	20, // 30: podoai.CommonService.DeleteScan:input_type -> podoai.DeleteScanRequest
	22, // 31: podoai.CommonService.GetProduct:input_type -> podoai.GetProductRequest
	24, // 32: podoai.CommonService.GetExercise:input_type -> podoai.GetExerciseRequest
	26, // 33: podoai.CommonService.GetTherapy:input_type -> podoai.GetTherapyRequest
	29, // 34: podoai.CommonService.RequestOtp:output_type -> podoai.RequestOtpResponse
	32, // 35: podoai.CommonService.VerifyOtp:output_type -> podoai.LoginResponse
	32, // 36: podoai.CommonService.Login:output_type -> podoai.LoginResponse
	15, // 37: podoai.CommonService.GetScans:output_type -> podoai.GetScansResponse
	17, // 38: podoai.CommonService.GetScan:output_type -> podoai.GetScanResponse
	19, // 39: podoai.CommonService.CreateScan:output_type -> podoai.CreateScanResponse
	21, // 40: podoai.CommonService.DeleteScan:output_type -> podoai.DeleteScanResponse
	23, // 41: podoai.CommonService.GetProduct:output_type -> podoai.GetProductResponse
	25, // 42: podoai.CommonService.GetExercise:output_type -> podoai.GetExerciseResponse
	27, // 43: podoai.CommonService.GetTherapy:output_type -> podoai.GetTherapyResponse
	34, // [34:44] is the sub-list for method output_type
	24, // [24:34] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_common_podoai_proto_init() }
func file_common_podoai_proto_init() {
	if File_common_podoai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_podoai_proto_rawDesc), len(file_common_podoai_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_podoai_proto_goTypes,
		DependencyIndexes: file_common_podoai_proto_depIdxs,
		EnumInfos:         file_common_podoai_proto_enumTypes,
		MessageInfos:      file_common_podoai_proto_msgTypes,
	}.Build()
	File_common_podoai_proto = out.File
	file_common_podoai_proto_goTypes = nil
	file_common_podoai_proto_depIdxs = nil
}
