// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: common/podoai.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageType int32

const (
	ImageType_IMAGE_TYPE_UNSPECIFIED  ImageType = 0
	ImageType_LEFT_FOOT_DORSAL        ImageType = 1
	ImageType_LEFT_FOOT_PLANTAR       ImageType = 2
	ImageType_LEFT_FOOT_MEDIAL_SIDE   ImageType = 3
	ImageType_LEFT_FOOT_LATERAL_SIDE  ImageType = 4
	ImageType_LEFT_FOOT_ANTERIOR      ImageType = 5
	ImageType_LEFT_FOOT_POSTERIOR     ImageType = 6
	ImageType_RIGHT_FOOT_DORSAL       ImageType = 7
	ImageType_RIGHT_FOOT_PLANTAR      ImageType = 8
	ImageType_RIGHT_FOOT_MEDIAL_SIDE  ImageType = 9
	ImageType_RIGHT_FOOT_LATERAL_SIDE ImageType = 10
	ImageType_RIGHT_FOOT_ANTERIOR     ImageType = 11
	ImageType_RIGHT_FOOT_POSTERIOR    ImageType = 12
)

// Enum value maps for ImageType.
var (
	ImageType_name = map[int32]string{
		0:  "IMAGE_TYPE_UNSPECIFIED",
		1:  "LEFT_FOOT_DORSAL",
		2:  "LEFT_FOOT_PLANTAR",
		3:  "LEFT_FOOT_MEDIAL_SIDE",
		4:  "LEFT_FOOT_LATERAL_SIDE",
		5:  "LEFT_FOOT_ANTERIOR",
		6:  "LEFT_FOOT_POSTERIOR",
		7:  "RIGHT_FOOT_DORSAL",
		8:  "RIGHT_FOOT_PLANTAR",
		9:  "RIGHT_FOOT_MEDIAL_SIDE",
		10: "RIGHT_FOOT_LATERAL_SIDE",
		11: "RIGHT_FOOT_ANTERIOR",
		12: "RIGHT_FOOT_POSTERIOR",
	}
	ImageType_value = map[string]int32{
		"IMAGE_TYPE_UNSPECIFIED":  0,
		"LEFT_FOOT_DORSAL":        1,
		"LEFT_FOOT_PLANTAR":       2,
		"LEFT_FOOT_MEDIAL_SIDE":   3,
		"LEFT_FOOT_LATERAL_SIDE":  4,
		"LEFT_FOOT_ANTERIOR":      5,
		"LEFT_FOOT_POSTERIOR":     6,
		"RIGHT_FOOT_DORSAL":       7,
		"RIGHT_FOOT_PLANTAR":      8,
		"RIGHT_FOOT_MEDIAL_SIDE":  9,
		"RIGHT_FOOT_LATERAL_SIDE": 10,
		"RIGHT_FOOT_ANTERIOR":     11,
		"RIGHT_FOOT_POSTERIOR":    12,
	}
)

func (x ImageType) Enum() *ImageType {
	p := new(ImageType)
	*p = x
	return p
}

func (x ImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_podoai_proto_enumTypes[0].Descriptor()
}

func (ImageType) Type() protoreflect.EnumType {
	return &file_common_podoai_proto_enumTypes[0]
}

func (x ImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageType.Descriptor instead.
func (ImageType) EnumDescriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{0}
}

type VideoType int32

const (
	VideoType_VIDEO_TYPE_UNSPECIFIED VideoType = 0
	VideoType_GAIT_ANTERIOR          VideoType = 1
	VideoType_GAIT_POSTERIOR         VideoType = 2
	VideoType_GAIT_LATERAL_LEFT      VideoType = 3
	VideoType_GAIT_LATERAL_RIGHT     VideoType = 4
	VideoType_GAIT_OBLIQUE           VideoType = 5
	VideoType_BALANCE_STATIC         VideoType = 6
	VideoType_BALANCE_DYNAMIC        VideoType = 7
	VideoType_SQUAT_ASSESSMENT       VideoType = 8
	VideoType_HEEL_RAISE             VideoType = 9
	VideoType_TOE_WALK               VideoType = 10
	VideoType_HEEL_WALK              VideoType = 11
	VideoType_SINGLE_LEG_STANCE      VideoType = 12
)

// Enum value maps for VideoType.
var (
	VideoType_name = map[int32]string{
		0:  "VIDEO_TYPE_UNSPECIFIED",
		1:  "GAIT_ANTERIOR",
		2:  "GAIT_POSTERIOR",
		3:  "GAIT_LATERAL_LEFT",
		4:  "GAIT_LATERAL_RIGHT",
		5:  "GAIT_OBLIQUE",
		6:  "BALANCE_STATIC",
		7:  "BALANCE_DYNAMIC",
		8:  "SQUAT_ASSESSMENT",
		9:  "HEEL_RAISE",
		10: "TOE_WALK",
		11: "HEEL_WALK",
		12: "SINGLE_LEG_STANCE",
	}
	VideoType_value = map[string]int32{
		"VIDEO_TYPE_UNSPECIFIED": 0,
		"GAIT_ANTERIOR":          1,
		"GAIT_POSTERIOR":         2,
		"GAIT_LATERAL_LEFT":      3,
		"GAIT_LATERAL_RIGHT":     4,
		"GAIT_OBLIQUE":           5,
		"BALANCE_STATIC":         6,
		"BALANCE_DYNAMIC":        7,
		"SQUAT_ASSESSMENT":       8,
		"HEEL_RAISE":             9,
		"TOE_WALK":               10,
		"HEEL_WALK":              11,
		"SINGLE_LEG_STANCE":      12,
	}
)

func (x VideoType) Enum() *VideoType {
	p := new(VideoType)
	*p = x
	return p
}

func (x VideoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_podoai_proto_enumTypes[1].Descriptor()
}

func (VideoType) Type() protoreflect.EnumType {
	return &file_common_podoai_proto_enumTypes[1]
}

func (x VideoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoType.Descriptor instead.
func (VideoType) EnumDescriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{1}
}

type Role int32

const (
	Role_ROLE_UNSPECIFIED   Role = 0
	Role_SUPERADMIN         Role = 1
	Role_ADMIN              Role = 2
	Role_CLINIC_CHAIN_ADMIN Role = 3
	Role_CLINIC_ADMIN       Role = 4
	Role_CLINIC_STAFF       Role = 5
	Role_CONSUMER           Role = 6
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "SUPERADMIN",
		2: "ADMIN",
		3: "CLINIC_CHAIN_ADMIN",
		4: "CLINIC_ADMIN",
		5: "CLINIC_STAFF",
		6: "CONSUMER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED":   0,
		"SUPERADMIN":         1,
		"ADMIN":              2,
		"CLINIC_CHAIN_ADMIN": 3,
		"CLINIC_ADMIN":       4,
		"CLINIC_STAFF":       5,
		"CONSUMER":           6,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_common_podoai_proto_enumTypes[2].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_common_podoai_proto_enumTypes[2]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{2}
}

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_MALE               Gender = 1
	Gender_FEMALE             Gender = 2
	Gender_OTHER              Gender = 3
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "MALE",
		2: "FEMALE",
		3: "OTHER",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"MALE":               1,
		"FEMALE":             2,
		"OTHER":              3,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_common_podoai_proto_enumTypes[3].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_common_podoai_proto_enumTypes[3]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{3}
}

type Scan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	OwnerEntityId string                 `protobuf:"bytes,3,opt,name=owner_entity_id,json=ownerEntityId,proto3" json:"owner_entity_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Images        []*Image               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	Videos        []*Video               `protobuf:"bytes,7,rep,name=videos,proto3" json:"videos,omitempty"`
	ScanAiResult  *ScanAIResult          `protobuf:"bytes,8,opt,name=scan_ai_result,json=scanAiResult,proto3" json:"scan_ai_result,omitempty"`
	ScannedById   string                 `protobuf:"bytes,9,opt,name=scanned_by_id,json=scannedById,proto3" json:"scanned_by_id,omitempty"`
	ReviewedById  string                 `protobuf:"bytes,10,opt,name=reviewed_by_id,json=reviewedById,proto3" json:"reviewed_by_id,omitempty"`
	ReviewedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=reviewed_at,json=reviewedAt,proto3" json:"reviewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scan) Reset() {
	*x = Scan{}
	mi := &file_common_podoai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scan) ProtoMessage() {}

func (x *Scan) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scan.ProtoReflect.Descriptor instead.
func (*Scan) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{0}
}

func (x *Scan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Scan) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *Scan) GetOwnerEntityId() string {
	if x != nil {
		return x.OwnerEntityId
	}
	return ""
}

func (x *Scan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Scan) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Scan) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Scan) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *Scan) GetScanAiResult() *ScanAIResult {
	if x != nil {
		return x.ScanAiResult
	}
	return nil
}

func (x *Scan) GetScannedById() string {
	if x != nil {
		return x.ScannedById
	}
	return ""
}

func (x *Scan) GetReviewedById() string {
	if x != nil {
		return x.ReviewedById
	}
	return ""
}

func (x *Scan) GetReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReviewedAt
	}
	return nil
}

type ScanAIResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ArchType       string                 `protobuf:"bytes,1,opt,name=arch_type,json=archType,proto3" json:"arch_type,omitempty"`
	Pronation      string                 `protobuf:"bytes,2,opt,name=pronation,proto3" json:"pronation,omitempty"`
	BalanceScore   float32                `protobuf:"fixed32,3,opt,name=balance_score,json=balanceScore,proto3" json:"balance_score,omitempty"`
	LlmResult      *ScanLLMResult         `protobuf:"bytes,4,opt,name=llm_result,json=llmResult,proto3" json:"llm_result,omitempty"`
	Recommendation *ScanRecommendation    `protobuf:"bytes,5,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScanAIResult) Reset() {
	*x = ScanAIResult{}
	mi := &file_common_podoai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanAIResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanAIResult) ProtoMessage() {}

func (x *ScanAIResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanAIResult.ProtoReflect.Descriptor instead.
func (*ScanAIResult) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{1}
}

func (x *ScanAIResult) GetArchType() string {
	if x != nil {
		return x.ArchType
	}
	return ""
}

func (x *ScanAIResult) GetPronation() string {
	if x != nil {
		return x.Pronation
	}
	return ""
}

func (x *ScanAIResult) GetBalanceScore() float32 {
	if x != nil {
		return x.BalanceScore
	}
	return 0
}

func (x *ScanAIResult) GetLlmResult() *ScanLLMResult {
	if x != nil {
		return x.LlmResult
	}
	return nil
}

func (x *ScanAIResult) GetRecommendation() *ScanRecommendation {
	if x != nil {
		return x.Recommendation
	}
	return nil
}

type ScanLLMResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanLLMResult) Reset() {
	*x = ScanLLMResult{}
	mi := &file_common_podoai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanLLMResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanLLMResult) ProtoMessage() {}

func (x *ScanLLMResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanLLMResult.ProtoReflect.Descriptor instead.
func (*ScanLLMResult) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{2}
}

func (x *ScanLLMResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ScanRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Exercises     []*Exercise            `protobuf:"bytes,2,rep,name=exercises,proto3" json:"exercises,omitempty"`
	Therapies     []*Therapy             `protobuf:"bytes,3,rep,name=therapies,proto3" json:"therapies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRecommendation) Reset() {
	*x = ScanRecommendation{}
	mi := &file_common_podoai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRecommendation) ProtoMessage() {}

func (x *ScanRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRecommendation.ProtoReflect.Descriptor instead.
func (*ScanRecommendation) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{3}
}

func (x *ScanRecommendation) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ScanRecommendation) GetExercises() []*Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

func (x *ScanRecommendation) GetTherapies() []*Therapy {
	if x != nil {
		return x.Therapies
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,4,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	Category      *ProductCategory       `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Prices        []*ProductPrice        `protobuf:"bytes,6,rep,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_common_podoai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{4}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *Product) GetCategory() *ProductCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Product) GetPrices() []*ProductPrice {
	if x != nil {
		return x.Prices
	}
	return nil
}

type ProductCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCategory) Reset() {
	*x = ProductCategory{}
	mi := &file_common_podoai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCategory) ProtoMessage() {}

func (x *ProductCategory) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCategory.ProtoReflect.Descriptor instead.
func (*ProductCategory) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{5}
}

func (x *ProductCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductCategory) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type ProductPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductPrice) Reset() {
	*x = ProductPrice{}
	mi := &file_common_podoai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPrice) ProtoMessage() {}

func (x *ProductPrice) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPrice.ProtoReflect.Descriptor instead.
func (*ProductPrice) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{6}
}

func (x *ProductPrice) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductPrice) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductPrice) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Exercise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	mi := &file_common_podoai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{7}
}

func (x *Exercise) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Exercise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exercise) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Exercise) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type Therapy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Therapy) Reset() {
	*x = Therapy{}
	mi := &file_common_podoai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Therapy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Therapy) ProtoMessage() {}

func (x *Therapy) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Therapy.ProtoReflect.Descriptor instead.
func (*Therapy) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{8}
}

func (x *Therapy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Therapy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Therapy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Therapy) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ImageType              `protobuf:"varint,1,opt,name=type,proto3,enum=podoai.ImageType" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	CapturedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_common_podoai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{9}
}

func (x *Image) GetType() ImageType {
	if x != nil {
		return x.Type
	}
	return ImageType_IMAGE_TYPE_UNSPECIFIED
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          VideoType              `protobuf:"varint,1,opt,name=type,proto3,enum=podoai.VideoType" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	CapturedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_common_podoai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{10}
}

func (x *Video) GetType() VideoType {
	if x != nil {
		return x.Type
	}
	return VideoType_VIDEO_TYPE_UNSPECIFIED
}

func (x *Video) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Video) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Video) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

type Patient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	OwnerEntityId string                 `protobuf:"bytes,4,opt,name=owner_entity_id,json=ownerEntityId,proto3" json:"owner_entity_id,omitempty"`
	Age           int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Gender        Gender                 `protobuf:"varint,6,opt,name=gender,proto3,enum=podoai.Gender" json:"gender,omitempty"`
	FootSize      int32                  `protobuf:"varint,7,opt,name=foot_size,json=footSize,proto3" json:"foot_size,omitempty"`
	TotalScans    int32                  `protobuf:"varint,8,opt,name=total_scans,json=totalScans,proto3" json:"total_scans,omitempty"`
	LastScanDate  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_scan_date,json=lastScanDate,proto3" json:"last_scan_date,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Patient) Reset() {
	*x = Patient{}
	mi := &file_common_podoai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient) ProtoMessage() {}

func (x *Patient) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient.ProtoReflect.Descriptor instead.
func (*Patient) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{11}
}

func (x *Patient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Patient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Patient) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Patient) GetOwnerEntityId() string {
	if x != nil {
		return x.OwnerEntityId
	}
	return ""
}

func (x *Patient) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Patient) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *Patient) GetFootSize() int32 {
	if x != nil {
		return x.FootSize
	}
	return 0
}

func (x *Patient) GetTotalScans() int32 {
	if x != nil {
		return x.TotalScans
	}
	return 0
}

func (x *Patient) GetLastScanDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastScanDate
	}
	return nil
}

func (x *Patient) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetScansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	OwnerEntityId string                 `protobuf:"bytes,2,opt,name=owner_entity_id,json=ownerEntityId,proto3" json:"owner_entity_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // "asc" or "desc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScansRequest) Reset() {
	*x = GetScansRequest{}
	mi := &file_common_podoai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScansRequest) ProtoMessage() {}

func (x *GetScansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScansRequest.ProtoReflect.Descriptor instead.
func (*GetScansRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{12}
}

func (x *GetScansRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *GetScansRequest) GetOwnerEntityId() string {
	if x != nil {
		return x.OwnerEntityId
	}
	return ""
}

func (x *GetScansRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetScansRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetScansRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetScansRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type GetScansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scans         []*Scan                `protobuf:"bytes,1,rep,name=scans,proto3" json:"scans,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScansResponse) Reset() {
	*x = GetScansResponse{}
	mi := &file_common_podoai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScansResponse) ProtoMessage() {}

func (x *GetScansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScansResponse.ProtoReflect.Descriptor instead.
func (*GetScansResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{13}
}

func (x *GetScansResponse) GetScans() []*Scan {
	if x != nil {
		return x.Scans
	}
	return nil
}

func (x *GetScansResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	OwnerEntityId string                 `protobuf:"bytes,2,opt,name=owner_entity_id,json=ownerEntityId,proto3" json:"owner_entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanRequest) Reset() {
	*x = GetScanRequest{}
	mi := &file_common_podoai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanRequest) ProtoMessage() {}

func (x *GetScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanRequest.ProtoReflect.Descriptor instead.
func (*GetScanRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{14}
}

func (x *GetScanRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *GetScanRequest) GetOwnerEntityId() string {
	if x != nil {
		return x.OwnerEntityId
	}
	return ""
}

type GetScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scan          *Scan                  `protobuf:"bytes,1,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanResponse) Reset() {
	*x = GetScanResponse{}
	mi := &file_common_podoai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanResponse) ProtoMessage() {}

func (x *GetScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanResponse.ProtoReflect.Descriptor instead.
func (*GetScanResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{15}
}

func (x *GetScanResponse) GetScan() *Scan {
	if x != nil {
		return x.Scan
	}
	return nil
}

type CreateScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scan          *Scan                  `protobuf:"bytes,1,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScanRequest) Reset() {
	*x = CreateScanRequest{}
	mi := &file_common_podoai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScanRequest) ProtoMessage() {}

func (x *CreateScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScanRequest.ProtoReflect.Descriptor instead.
func (*CreateScanRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{16}
}

func (x *CreateScanRequest) GetScan() *Scan {
	if x != nil {
		return x.Scan
	}
	return nil
}

type CreateScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scan          *Scan                  `protobuf:"bytes,1,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScanResponse) Reset() {
	*x = CreateScanResponse{}
	mi := &file_common_podoai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScanResponse) ProtoMessage() {}

func (x *CreateScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScanResponse.ProtoReflect.Descriptor instead.
func (*CreateScanResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{17}
}

func (x *CreateScanResponse) GetScan() *Scan {
	if x != nil {
		return x.Scan
	}
	return nil
}

type UpdateScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scan          *Scan                  `protobuf:"bytes,1,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScanRequest) Reset() {
	*x = UpdateScanRequest{}
	mi := &file_common_podoai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScanRequest) ProtoMessage() {}

func (x *UpdateScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScanRequest.ProtoReflect.Descriptor instead.
func (*UpdateScanRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateScanRequest) GetScan() *Scan {
	if x != nil {
		return x.Scan
	}
	return nil
}

type UpdateScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scan          *Scan                  `protobuf:"bytes,1,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScanResponse) Reset() {
	*x = UpdateScanResponse{}
	mi := &file_common_podoai_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScanResponse) ProtoMessage() {}

func (x *UpdateScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScanResponse.ProtoReflect.Descriptor instead.
func (*UpdateScanResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateScanResponse) GetScan() *Scan {
	if x != nil {
		return x.Scan
	}
	return nil
}

type DeleteScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	OwnerEntityId string                 `protobuf:"bytes,2,opt,name=owner_entity_id,json=ownerEntityId,proto3" json:"owner_entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScanRequest) Reset() {
	*x = DeleteScanRequest{}
	mi := &file_common_podoai_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScanRequest) ProtoMessage() {}

func (x *DeleteScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScanRequest.ProtoReflect.Descriptor instead.
func (*DeleteScanRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteScanRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *DeleteScanRequest) GetOwnerEntityId() string {
	if x != nil {
		return x.OwnerEntityId
	}
	return ""
}

type DeleteScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScanResponse) Reset() {
	*x = DeleteScanResponse{}
	mi := &file_common_podoai_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScanResponse) ProtoMessage() {}

func (x *DeleteScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScanResponse.ProtoReflect.Descriptor instead.
func (*DeleteScanResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteScanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_common_podoai_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{22}
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_common_podoai_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{23}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseRequest) Reset() {
	*x = GetExerciseRequest{}
	mi := &file_common_podoai_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseRequest) ProtoMessage() {}

func (x *GetExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseRequest.ProtoReflect.Descriptor instead.
func (*GetExerciseRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{24}
}

func (x *GetExerciseRequest) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

type GetExerciseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercise      *Exercise              `protobuf:"bytes,1,opt,name=exercise,proto3" json:"exercise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseResponse) Reset() {
	*x = GetExerciseResponse{}
	mi := &file_common_podoai_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseResponse) ProtoMessage() {}

func (x *GetExerciseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseResponse.ProtoReflect.Descriptor instead.
func (*GetExerciseResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{25}
}

func (x *GetExerciseResponse) GetExercise() *Exercise {
	if x != nil {
		return x.Exercise
	}
	return nil
}

type GetTherapyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapyId     string                 `protobuf:"bytes,1,opt,name=therapy_id,json=therapyId,proto3" json:"therapy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTherapyRequest) Reset() {
	*x = GetTherapyRequest{}
	mi := &file_common_podoai_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTherapyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTherapyRequest) ProtoMessage() {}

func (x *GetTherapyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTherapyRequest.ProtoReflect.Descriptor instead.
func (*GetTherapyRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{26}
}

func (x *GetTherapyRequest) GetTherapyId() string {
	if x != nil {
		return x.TherapyId
	}
	return ""
}

type GetTherapyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Therapy       *Therapy               `protobuf:"bytes,1,opt,name=therapy,proto3" json:"therapy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTherapyResponse) Reset() {
	*x = GetTherapyResponse{}
	mi := &file_common_podoai_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTherapyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTherapyResponse) ProtoMessage() {}

func (x *GetTherapyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTherapyResponse.ProtoReflect.Descriptor instead.
func (*GetTherapyResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{27}
}

func (x *GetTherapyResponse) GetTherapy() *Therapy {
	if x != nil {
		return x.Therapy
	}
	return nil
}

// ===== Authentication =====
type RequestOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOtpRequest) Reset() {
	*x = RequestOtpRequest{}
	mi := &file_common_podoai_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOtpRequest) ProtoMessage() {}

func (x *RequestOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOtpRequest.ProtoReflect.Descriptor instead.
func (*RequestOtpRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{28}
}

func (x *RequestOtpRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type RequestOtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOtpResponse) Reset() {
	*x = RequestOtpResponse{}
	mi := &file_common_podoai_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOtpResponse) ProtoMessage() {}

func (x *RequestOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOtpResponse.ProtoReflect.Descriptor instead.
func (*RequestOtpResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{29}
}

func (x *RequestOtpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RequestOtpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOtpRequest) Reset() {
	*x = VerifyOtpRequest{}
	mi := &file_common_podoai_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOtpRequest) ProtoMessage() {}

func (x *VerifyOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOtpRequest.ProtoReflect.Descriptor instead.
func (*VerifyOtpRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{30}
}

func (x *VerifyOtpRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *VerifyOtpRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Roles         []Role                 `protobuf:"varint,3,rep,packed,name=roles,proto3,enum=podoai.Role" json:"roles,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_common_podoai_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{31}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetRoles() []Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Patient API messages
type GetPatientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerEntityId string                 `protobuf:"bytes,1,opt,name=owner_entity_id,json=ownerEntityId,proto3" json:"owner_entity_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // "asc" or "desc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientsRequest) Reset() {
	*x = GetPatientsRequest{}
	mi := &file_common_podoai_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientsRequest) ProtoMessage() {}

func (x *GetPatientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientsRequest.ProtoReflect.Descriptor instead.
func (*GetPatientsRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{32}
}

func (x *GetPatientsRequest) GetOwnerEntityId() string {
	if x != nil {
		return x.OwnerEntityId
	}
	return ""
}

func (x *GetPatientsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPatientsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPatientsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetPatientsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type GetPatientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*Patient             `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientsResponse) Reset() {
	*x = GetPatientsResponse{}
	mi := &file_common_podoai_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientsResponse) ProtoMessage() {}

func (x *GetPatientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientsResponse.ProtoReflect.Descriptor instead.
func (*GetPatientsResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{33}
}

func (x *GetPatientsResponse) GetPatients() []*Patient {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *GetPatientsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	OwnerEntityId string                 `protobuf:"bytes,2,opt,name=owner_entity_id,json=ownerEntityId,proto3" json:"owner_entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientRequest) Reset() {
	*x = GetPatientRequest{}
	mi := &file_common_podoai_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientRequest) ProtoMessage() {}

func (x *GetPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientRequest.ProtoReflect.Descriptor instead.
func (*GetPatientRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{34}
}

func (x *GetPatientRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *GetPatientRequest) GetOwnerEntityId() string {
	if x != nil {
		return x.OwnerEntityId
	}
	return ""
}

type GetPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientResponse) Reset() {
	*x = GetPatientResponse{}
	mi := &file_common_podoai_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientResponse) ProtoMessage() {}

func (x *GetPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientResponse.ProtoReflect.Descriptor instead.
func (*GetPatientResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{35}
}

func (x *GetPatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

type SearchPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchTerm    string                 `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	OwnerEntityId string                 `protobuf:"bytes,2,opt,name=owner_entity_id,json=ownerEntityId,proto3" json:"owner_entity_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPatientRequest) Reset() {
	*x = SearchPatientRequest{}
	mi := &file_common_podoai_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPatientRequest) ProtoMessage() {}

func (x *SearchPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPatientRequest.ProtoReflect.Descriptor instead.
func (*SearchPatientRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{36}
}

func (x *SearchPatientRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

func (x *SearchPatientRequest) GetOwnerEntityId() string {
	if x != nil {
		return x.OwnerEntityId
	}
	return ""
}

func (x *SearchPatientRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchPatientRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*Patient             `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPatientResponse) Reset() {
	*x = SearchPatientResponse{}
	mi := &file_common_podoai_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPatientResponse) ProtoMessage() {}

func (x *SearchPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPatientResponse.ProtoReflect.Descriptor instead.
func (*SearchPatientResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{37}
}

func (x *SearchPatientResponse) GetPatients() []*Patient {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *SearchPatientResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreatePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePatientRequest) Reset() {
	*x = CreatePatientRequest{}
	mi := &file_common_podoai_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePatientRequest) ProtoMessage() {}

func (x *CreatePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePatientRequest.ProtoReflect.Descriptor instead.
func (*CreatePatientRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{38}
}

func (x *CreatePatientRequest) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

type CreatePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePatientResponse) Reset() {
	*x = CreatePatientResponse{}
	mi := &file_common_podoai_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePatientResponse) ProtoMessage() {}

func (x *CreatePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePatientResponse.ProtoReflect.Descriptor instead.
func (*CreatePatientResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{39}
}

func (x *CreatePatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

type DeletePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	OwnerEntityId string                 `protobuf:"bytes,2,opt,name=owner_entity_id,json=ownerEntityId,proto3" json:"owner_entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePatientRequest) Reset() {
	*x = DeletePatientRequest{}
	mi := &file_common_podoai_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePatientRequest) ProtoMessage() {}

func (x *DeletePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePatientRequest.ProtoReflect.Descriptor instead.
func (*DeletePatientRequest) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{40}
}

func (x *DeletePatientRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *DeletePatientRequest) GetOwnerEntityId() string {
	if x != nil {
		return x.OwnerEntityId
	}
	return ""
}

type DeletePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePatientResponse) Reset() {
	*x = DeletePatientResponse{}
	mi := &file_common_podoai_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePatientResponse) ProtoMessage() {}

func (x *DeletePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_podoai_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePatientResponse.ProtoReflect.Descriptor instead.
func (*DeletePatientResponse) Descriptor() ([]byte, []int) {
	return file_common_podoai_proto_rawDescGZIP(), []int{41}
}

func (x *DeletePatientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_common_podoai_proto protoreflect.FileDescriptor

const file_common_podoai_proto_rawDesc = "" +
	"\n" +
	"\x13common/podoai.proto\x12\x06podoai\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x03\n" +
	"\x04Scan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12&\n" +
	"\x0fowner_entity_id\x18\x03 \x01(\tR\rownerEntityId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12%\n" +
	"\x06images\x18\x06 \x03(\v2\r.podoai.ImageR\x06images\x12%\n" +
	"\x06videos\x18\a \x03(\v2\r.podoai.VideoR\x06videos\x12:\n" +
	"\x0escan_ai_result\x18\b \x01(\v2\x14.podoai.ScanAIResultR\fscanAiResult\x12\"\n" +
	"\rscanned_by_id\x18\t \x01(\tR\vscannedById\x12$\n" +
	"\x0ereviewed_by_id\x18\n" +
	" \x01(\tR\freviewedById\x12;\n" +
	"\vreviewed_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reviewedAt\"\xe8\x01\n" +
	"\fScanAIResult\x12\x1b\n" +
	"\tarch_type\x18\x01 \x01(\tR\barchType\x12\x1c\n" +
	"\tpronation\x18\x02 \x01(\tR\tpronation\x12#\n" +
	"\rbalance_score\x18\x03 \x01(\x02R\fbalanceScore\x124\n" +
	"\n" +
	"llm_result\x18\x04 \x01(\v2\x15.podoai.ScanLLMResultR\tllmResult\x12B\n" +
	"\x0erecommendation\x18\x05 \x01(\v2\x1a.podoai.ScanRecommendationR\x0erecommendation\")\n" +
	"\rScanLLMResult\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\"\xa0\x01\n" +
	"\x12ScanRecommendation\x12+\n" +
	"\bproducts\x18\x01 \x03(\v2\x0f.podoai.ProductR\bproducts\x12.\n" +
	"\texercises\x18\x02 \x03(\v2\x10.podoai.ExerciseR\texercises\x12-\n" +
	"\ttherapies\x18\x03 \x03(\v2\x0f.podoai.TherapyR\ttherapies\"\xd1\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x04 \x03(\tR\tmediaUrls\x123\n" +
	"\bcategory\x18\x05 \x01(\v2\x17.podoai.ProductCategoryR\bcategory\x12,\n" +
	"\x06prices\x18\x06 \x03(\v2\x14.podoai.ProductPriceR\x06prices\"t\n" +
	"\x0fProductCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\"_\n" +
	"\fProductPrice\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"m\n" +
	"\bExercise\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\"l\n" +
	"\aTherapy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\"}\n" +
	"\x05Image\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.podoai.ImageTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12;\n" +
	"\vcaptured_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\"\x99\x01\n" +
	"\x05Video\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.podoai.VideoTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12;\n" +
	"\vcaptured_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\"\xed\x02\n" +
	"\aPatient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12&\n" +
	"\x0fowner_entity_id\x18\x04 \x01(\tR\rownerEntityId\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\x12&\n" +
	"\x06gender\x18\x06 \x01(\x0e2\x0e.podoai.GenderR\x06gender\x12\x1b\n" +
	"\tfoot_size\x18\a \x01(\x05R\bfootSize\x12\x1f\n" +
	"\vtotal_scans\x18\b \x01(\x05R\n" +
	"totalScans\x12@\n" +
	"\x0elast_scan_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\flastScanDate\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc1\x01\n" +
	"\x0fGetScansRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12&\n" +
	"\x0fowner_entity_id\x18\x02 \x01(\tR\rownerEntityId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\tR\tsortOrder\"W\n" +
	"\x10GetScansResponse\x12\"\n" +
	"\x05scans\x18\x01 \x03(\v2\f.podoai.ScanR\x05scans\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"Q\n" +
	"\x0eGetScanRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12&\n" +
	"\x0fowner_entity_id\x18\x02 \x01(\tR\rownerEntityId\"3\n" +
	"\x0fGetScanResponse\x12 \n" +
	"\x04scan\x18\x01 \x01(\v2\f.podoai.ScanR\x04scan\"5\n" +
	"\x11CreateScanRequest\x12 \n" +
	"\x04scan\x18\x01 \x01(\v2\f.podoai.ScanR\x04scan\"6\n" +
	"\x12CreateScanResponse\x12 \n" +
	"\x04scan\x18\x01 \x01(\v2\f.podoai.ScanR\x04scan\"5\n" +
	"\x11UpdateScanRequest\x12 \n" +
	"\x04scan\x18\x01 \x01(\v2\f.podoai.ScanR\x04scan\"6\n" +
	"\x12UpdateScanResponse\x12 \n" +
	"\x04scan\x18\x01 \x01(\v2\f.podoai.ScanR\x04scan\"T\n" +
	"\x11DeleteScanRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12&\n" +
	"\x0fowner_entity_id\x18\x02 \x01(\tR\rownerEntityId\".\n" +
	"\x12DeleteScanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"?\n" +
	"\x12GetProductResponse\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.podoai.ProductR\aproduct\"5\n" +
	"\x12GetExerciseRequest\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\"C\n" +
	"\x13GetExerciseResponse\x12,\n" +
	"\bexercise\x18\x01 \x01(\v2\x10.podoai.ExerciseR\bexercise\"2\n" +
	"\x11GetTherapyRequest\x12\x1d\n" +
	"\n" +
	"therapy_id\x18\x01 \x01(\tR\ttherapyId\"?\n" +
	"\x12GetTherapyResponse\x12)\n" +
	"\atherapy\x18\x01 \x01(\v2\x0f.podoai.TherapyR\atherapy\"6\n" +
	"\x11RequestOtpRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"H\n" +
	"\x12RequestOtpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x10VerifyOtpRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"\x87\x01\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\"\n" +
	"\x05roles\x18\x03 \x03(\x0e2\f.podoai.RoleR\x05roles\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\xa5\x01\n" +
	"\x12GetPatientsRequest\x12&\n" +
	"\x0fowner_entity_id\x18\x01 \x01(\tR\rownerEntityId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x04 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\tR\tsortOrder\"c\n" +
	"\x13GetPatientsResponse\x12+\n" +
	"\bpatients\x18\x01 \x03(\v2\x0f.podoai.PatientR\bpatients\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"Z\n" +
	"\x11GetPatientRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12&\n" +
	"\x0fowner_entity_id\x18\x02 \x01(\tR\rownerEntityId\"?\n" +
	"\x12GetPatientResponse\x12)\n" +
	"\apatient\x18\x01 \x01(\v2\x0f.podoai.PatientR\apatient\"\x90\x01\n" +
	"\x14SearchPatientRequest\x12\x1f\n" +
	"\vsearch_term\x18\x01 \x01(\tR\n" +
	"searchTerm\x12&\n" +
	"\x0fowner_entity_id\x18\x02 \x01(\tR\rownerEntityId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"e\n" +
	"\x15SearchPatientResponse\x12+\n" +
	"\bpatients\x18\x01 \x03(\v2\x0f.podoai.PatientR\bpatients\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"A\n" +
	"\x14CreatePatientRequest\x12)\n" +
	"\apatient\x18\x01 \x01(\v2\x0f.podoai.PatientR\apatient\"B\n" +
	"\x15CreatePatientResponse\x12)\n" +
	"\apatient\x18\x01 \x01(\v2\x0f.podoai.PatientR\apatient\"]\n" +
	"\x14DeletePatientRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12&\n" +
	"\x0fowner_entity_id\x18\x02 \x01(\tR\rownerEntityId\"1\n" +
	"\x15DeletePatientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xd7\x02\n" +
	"\tImageType\x12\x1a\n" +
	"\x16IMAGE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10LEFT_FOOT_DORSAL\x10\x01\x12\x15\n" +
	"\x11LEFT_FOOT_PLANTAR\x10\x02\x12\x19\n" +
	"\x15LEFT_FOOT_MEDIAL_SIDE\x10\x03\x12\x1a\n" +
	"\x16LEFT_FOOT_LATERAL_SIDE\x10\x04\x12\x16\n" +
	"\x12LEFT_FOOT_ANTERIOR\x10\x05\x12\x17\n" +
	"\x13LEFT_FOOT_POSTERIOR\x10\x06\x12\x15\n" +
	"\x11RIGHT_FOOT_DORSAL\x10\a\x12\x16\n" +
	"\x12RIGHT_FOOT_PLANTAR\x10\b\x12\x1a\n" +
	"\x16RIGHT_FOOT_MEDIAL_SIDE\x10\t\x12\x1b\n" +
	"\x17RIGHT_FOOT_LATERAL_SIDE\x10\n" +
	"\x12\x17\n" +
	"\x13RIGHT_FOOT_ANTERIOR\x10\v\x12\x18\n" +
	"\x14RIGHT_FOOT_POSTERIOR\x10\f*\x92\x02\n" +
	"\tVideoType\x12\x1a\n" +
	"\x16VIDEO_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rGAIT_ANTERIOR\x10\x01\x12\x12\n" +
	"\x0eGAIT_POSTERIOR\x10\x02\x12\x15\n" +
	"\x11GAIT_LATERAL_LEFT\x10\x03\x12\x16\n" +
	"\x12GAIT_LATERAL_RIGHT\x10\x04\x12\x10\n" +
	"\fGAIT_OBLIQUE\x10\x05\x12\x12\n" +
	"\x0eBALANCE_STATIC\x10\x06\x12\x13\n" +
	"\x0fBALANCE_DYNAMIC\x10\a\x12\x14\n" +
	"\x10SQUAT_ASSESSMENT\x10\b\x12\x0e\n" +
	"\n" +
	"HEEL_RAISE\x10\t\x12\f\n" +
	"\bTOE_WALK\x10\n" +
	"\x12\r\n" +
	"\tHEEL_WALK\x10\v\x12\x15\n" +
	"\x11SINGLE_LEG_STANCE\x10\f*\x81\x01\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"SUPERADMIN\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02\x12\x16\n" +
	"\x12CLINIC_CHAIN_ADMIN\x10\x03\x12\x10\n" +
	"\fCLINIC_ADMIN\x10\x04\x12\x10\n" +
	"\fCLINIC_STAFF\x10\x05\x12\f\n" +
	"\bCONSUMER\x10\x06*A\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04MALE\x10\x01\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x02\x12\t\n" +
	"\x05OTHER\x10\x032\xa5\b\n" +
	"\rCommonService\x12C\n" +
	"\n" +
	"RequestOtp\x12\x19.podoai.RequestOtpRequest\x1a\x1a.podoai.RequestOtpResponse\x12<\n" +
	"\tVerifyOtp\x12\x18.podoai.VerifyOtpRequest\x1a\x15.podoai.LoginResponse\x12=\n" +
	"\bGetScans\x12\x17.podoai.GetScansRequest\x1a\x18.podoai.GetScansResponse\x12:\n" +
	"\aGetScan\x12\x16.podoai.GetScanRequest\x1a\x17.podoai.GetScanResponse\x12C\n" +
	"\n" +
	"CreateScan\x12\x19.podoai.CreateScanRequest\x1a\x1a.podoai.CreateScanResponse\x12C\n" +
	"\n" +
	"UpdateScan\x12\x19.podoai.UpdateScanRequest\x1a\x1a.podoai.UpdateScanResponse\x12C\n" +
	"\n" +
	"DeleteScan\x12\x19.podoai.DeleteScanRequest\x1a\x1a.podoai.DeleteScanResponse\x12C\n" +
	"\n" +
	"GetProduct\x12\x19.podoai.GetProductRequest\x1a\x1a.podoai.GetProductResponse\x12F\n" +
	"\vGetExercise\x12\x1a.podoai.GetExerciseRequest\x1a\x1b.podoai.GetExerciseResponse\x12C\n" +
	"\n" +
	"GetTherapy\x12\x19.podoai.GetTherapyRequest\x1a\x1a.podoai.GetTherapyResponse\x12F\n" +
	"\vGetPatients\x12\x1a.podoai.GetPatientsRequest\x1a\x1b.podoai.GetPatientsResponse\x12C\n" +
	"\n" +
	"GetPatient\x12\x19.podoai.GetPatientRequest\x1a\x1a.podoai.GetPatientResponse\x12L\n" +
	"\rSearchPatient\x12\x1c.podoai.SearchPatientRequest\x1a\x1d.podoai.SearchPatientResponse\x12L\n" +
	"\rCreatePatient\x12\x1c.podoai.CreatePatientRequest\x1a\x1d.podoai.CreatePatientResponse\x12L\n" +
	"\rDeletePatient\x12\x1c.podoai.DeletePatientRequest\x1a\x1d.podoai.DeletePatientResponseB/Z-github.com/therehabstreet/podoai/proto/commonb\x06proto3"

var (
	file_common_podoai_proto_rawDescOnce sync.Once
	file_common_podoai_proto_rawDescData []byte
)

func file_common_podoai_proto_rawDescGZIP() []byte {
	file_common_podoai_proto_rawDescOnce.Do(func() {
		file_common_podoai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_podoai_proto_rawDesc), len(file_common_podoai_proto_rawDesc)))
	})
	return file_common_podoai_proto_rawDescData
}

var file_common_podoai_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_common_podoai_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_common_podoai_proto_goTypes = []any{
	(ImageType)(0),                // 0: podoai.ImageType
	(VideoType)(0),                // 1: podoai.VideoType
	(Role)(0),                     // 2: podoai.Role
	(Gender)(0),                   // 3: podoai.Gender
	(*Scan)(nil),                  // 4: podoai.Scan
	(*ScanAIResult)(nil),          // 5: podoai.ScanAIResult
	(*ScanLLMResult)(nil),         // 6: podoai.ScanLLMResult
	(*ScanRecommendation)(nil),    // 7: podoai.ScanRecommendation
	(*Product)(nil),               // 8: podoai.Product
	(*ProductCategory)(nil),       // 9: podoai.ProductCategory
	(*ProductPrice)(nil),          // 10: podoai.ProductPrice
	(*Exercise)(nil),              // 11: podoai.Exercise
	(*Therapy)(nil),               // 12: podoai.Therapy
	(*Image)(nil),                 // 13: podoai.Image
	(*Video)(nil),                 // 14: podoai.Video
	(*Patient)(nil),               // 15: podoai.Patient
	(*GetScansRequest)(nil),       // 16: podoai.GetScansRequest
	(*GetScansResponse)(nil),      // 17: podoai.GetScansResponse
	(*GetScanRequest)(nil),        // 18: podoai.GetScanRequest
	(*GetScanResponse)(nil),       // 19: podoai.GetScanResponse
	(*CreateScanRequest)(nil),     // 20: podoai.CreateScanRequest
	(*CreateScanResponse)(nil),    // 21: podoai.CreateScanResponse
	(*UpdateScanRequest)(nil),     // 22: podoai.UpdateScanRequest
	(*UpdateScanResponse)(nil),    // 23: podoai.UpdateScanResponse
	(*DeleteScanRequest)(nil),     // 24: podoai.DeleteScanRequest
	(*DeleteScanResponse)(nil),    // 25: podoai.DeleteScanResponse
	(*GetProductRequest)(nil),     // 26: podoai.GetProductRequest
	(*GetProductResponse)(nil),    // 27: podoai.GetProductResponse
	(*GetExerciseRequest)(nil),    // 28: podoai.GetExerciseRequest
	(*GetExerciseResponse)(nil),   // 29: podoai.GetExerciseResponse
	(*GetTherapyRequest)(nil),     // 30: podoai.GetTherapyRequest
	(*GetTherapyResponse)(nil),    // 31: podoai.GetTherapyResponse
	(*RequestOtpRequest)(nil),     // 32: podoai.RequestOtpRequest
	(*RequestOtpResponse)(nil),    // 33: podoai.RequestOtpResponse
	(*VerifyOtpRequest)(nil),      // 34: podoai.VerifyOtpRequest
	(*LoginResponse)(nil),         // 35: podoai.LoginResponse
	(*GetPatientsRequest)(nil),    // 36: podoai.GetPatientsRequest
	(*GetPatientsResponse)(nil),   // 37: podoai.GetPatientsResponse
	(*GetPatientRequest)(nil),     // 38: podoai.GetPatientRequest
	(*GetPatientResponse)(nil),    // 39: podoai.GetPatientResponse
	(*SearchPatientRequest)(nil),  // 40: podoai.SearchPatientRequest
	(*SearchPatientResponse)(nil), // 41: podoai.SearchPatientResponse
	(*CreatePatientRequest)(nil),  // 42: podoai.CreatePatientRequest
	(*CreatePatientResponse)(nil), // 43: podoai.CreatePatientResponse
	(*DeletePatientRequest)(nil),  // 44: podoai.DeletePatientRequest
	(*DeletePatientResponse)(nil), // 45: podoai.DeletePatientResponse
	(*timestamppb.Timestamp)(nil), // 46: google.protobuf.Timestamp
}
var file_common_podoai_proto_depIdxs = []int32{
	46, // 0: podoai.Scan.created_at:type_name -> google.protobuf.Timestamp
	46, // 1: podoai.Scan.updated_at:type_name -> google.protobuf.Timestamp
	13, // 2: podoai.Scan.images:type_name -> podoai.Image
	14, // 3: podoai.Scan.videos:type_name -> podoai.Video
	5,  // 4: podoai.Scan.scan_ai_result:type_name -> podoai.ScanAIResult
	46, // 5: podoai.Scan.reviewed_at:type_name -> google.protobuf.Timestamp
	6,  // 6: podoai.ScanAIResult.llm_result:type_name -> podoai.ScanLLMResult
	7,  // 7: podoai.ScanAIResult.recommendation:type_name -> podoai.ScanRecommendation
	8,  // 8: podoai.ScanRecommendation.products:type_name -> podoai.Product
	11, // 9: podoai.ScanRecommendation.exercises:type_name -> podoai.Exercise
	12, // 10: podoai.ScanRecommendation.therapies:type_name -> podoai.Therapy
	9,  // 11: podoai.Product.category:type_name -> podoai.ProductCategory
	10, // 12: podoai.Product.prices:type_name -> podoai.ProductPrice
	0,  // 13: podoai.Image.type:type_name -> podoai.ImageType
	46, // 14: podoai.Image.captured_at:type_name -> google.protobuf.Timestamp
	1,  // 15: podoai.Video.type:type_name -> podoai.VideoType
	46, // 16: podoai.Video.captured_at:type_name -> google.protobuf.Timestamp
	3,  // 17: podoai.Patient.gender:type_name -> podoai.Gender
	46, // 18: podoai.Patient.last_scan_date:type_name -> google.protobuf.Timestamp
	46, // 19: podoai.Patient.created_at:type_name -> google.protobuf.Timestamp
	4,  // 20: podoai.GetScansResponse.scans:type_name -> podoai.Scan
	4,  // 21: podoai.GetScanResponse.scan:type_name -> podoai.Scan
	4,  // 22: podoai.CreateScanRequest.scan:type_name -> podoai.Scan
	4,  // 23: podoai.CreateScanResponse.scan:type_name -> podoai.Scan
	4,  // 24: podoai.UpdateScanRequest.scan:type_name -> podoai.Scan
	4,  // 25: podoai.UpdateScanResponse.scan:type_name -> podoai.Scan
	8,  // 26: podoai.GetProductResponse.product:type_name -> podoai.Product
	11, // 27: podoai.GetExerciseResponse.exercise:type_name -> podoai.Exercise
	12, // 28: podoai.GetTherapyResponse.therapy:type_name -> podoai.Therapy
	2,  // 29: podoai.LoginResponse.roles:type_name -> podoai.Role
	15, // 30: podoai.GetPatientsResponse.patients:type_name -> podoai.Patient
	15, // 31: podoai.GetPatientResponse.patient:type_name -> podoai.Patient
	15, // 32: podoai.SearchPatientResponse.patients:type_name -> podoai.Patient
	15, // 33: podoai.CreatePatientRequest.patient:type_name -> podoai.Patient
	15, // 34: podoai.CreatePatientResponse.patient:type_name -> podoai.Patient
	32, // 35: podoai.CommonService.RequestOtp:input_type -> podoai.RequestOtpRequest
	34, // 36: podoai.CommonService.VerifyOtp:input_type -> podoai.VerifyOtpRequest
	16, // 37: podoai.CommonService.GetScans:input_type -> podoai.GetScansRequest
	18, // 38: podoai.CommonService.GetScan:input_type -> podoai.GetScanRequest
	20, // 39: podoai.CommonService.CreateScan:input_type -> podoai.CreateScanRequest
	22, // 40: podoai.CommonService.UpdateScan:input_type -> podoai.UpdateScanRequest
	24, // 41: podoai.CommonService.DeleteScan:input_type -> podoai.DeleteScanRequest
	26, // 42: podoai.CommonService.GetProduct:input_type -> podoai.GetProductRequest
	28, // 43: podoai.CommonService.GetExercise:input_type -> podoai.GetExerciseRequest
	30, // 44: podoai.CommonService.GetTherapy:input_type -> podoai.GetTherapyRequest
	36, // 45: podoai.CommonService.GetPatients:input_type -> podoai.GetPatientsRequest
	38, // 46: podoai.CommonService.GetPatient:input_type -> podoai.GetPatientRequest
	40, // 47: podoai.CommonService.SearchPatient:input_type -> podoai.SearchPatientRequest
	42, // 48: podoai.CommonService.CreatePatient:input_type -> podoai.CreatePatientRequest
	44, // 49: podoai.CommonService.DeletePatient:input_type -> podoai.DeletePatientRequest
	33, // 50: podoai.CommonService.RequestOtp:output_type -> podoai.RequestOtpResponse
	35, // 51: podoai.CommonService.VerifyOtp:output_type -> podoai.LoginResponse
	17, // 52: podoai.CommonService.GetScans:output_type -> podoai.GetScansResponse
	19, // 53: podoai.CommonService.GetScan:output_type -> podoai.GetScanResponse
	21, // 54: podoai.CommonService.CreateScan:output_type -> podoai.CreateScanResponse
	23, // 55: podoai.CommonService.UpdateScan:output_type -> podoai.UpdateScanResponse
	25, // 56: podoai.CommonService.DeleteScan:output_type -> podoai.DeleteScanResponse
	27, // 57: podoai.CommonService.GetProduct:output_type -> podoai.GetProductResponse
	29, // 58: podoai.CommonService.GetExercise:output_type -> podoai.GetExerciseResponse
	31, // 59: podoai.CommonService.GetTherapy:output_type -> podoai.GetTherapyResponse
	37, // 60: podoai.CommonService.GetPatients:output_type -> podoai.GetPatientsResponse
	39, // 61: podoai.CommonService.GetPatient:output_type -> podoai.GetPatientResponse
	41, // 62: podoai.CommonService.SearchPatient:output_type -> podoai.SearchPatientResponse
	43, // 63: podoai.CommonService.CreatePatient:output_type -> podoai.CreatePatientResponse
	45, // 64: podoai.CommonService.DeletePatient:output_type -> podoai.DeletePatientResponse
	50, // [50:65] is the sub-list for method output_type
	35, // [35:50] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_common_podoai_proto_init() }
func file_common_podoai_proto_init() {
	if File_common_podoai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_podoai_proto_rawDesc), len(file_common_podoai_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_podoai_proto_goTypes,
		DependencyIndexes: file_common_podoai_proto_depIdxs,
		EnumInfos:         file_common_podoai_proto_enumTypes,
		MessageInfos:      file_common_podoai_proto_msgTypes,
	}.Build()
	File_common_podoai_proto = out.File
	file_common_podoai_proto_goTypes = nil
	file_common_podoai_proto_depIdxs = nil
}
